import os
import io
from PIL import Image

base_ws = r"C:\Program Files (x86)\Steam\steamapps\workshop\content\394360\3106240385\gfx\interface\goals"

focus_mapping = [
    # Phase I (1911-1914)
    {
        "focus_id": "GER_agadir_crisis_gambit",
        "phase": "Phase I (1911-1914)",
        "name_pt": "O Salto da Pantera em Agadir (Julho de 1911)",
        "sprite": "GFX_focus_GER_agadir_crisis_gambit",
        "dds_name": "focus_GER_agadir_crisis_gambit.dds",
        "source_path": os.path.join(base_ws, "GFX_FRA_agadir_crisis-69194.dds"),
        "visual_desc": "Canhoneira Panther e bandeiras em crise marroquina",
        "is_source_dds": True,
    },
    {
        "focus_id": "GER_tirpitz_fourth_naval_bill",
        "phase": "Phase I (1911-1914)",
        "name_pt": "A Quarta Novela Naval de Tirpitz (1912)",
        "sprite": "GFX_focus_GER_navy",
        "dds_name": "focus_GER_navy.dds",
        "source_path": os.path.join(base_ws, "GER", "focus_GER_navy.png"),
        "visual_desc": "Linha de Dreadnoughts da Hochseeflotte em formação de batalha",
        "is_source_dds": False,
    },
    {
        "focus_id": "GER_berlin_baghdad_railway",
        "phase": "Phase I (1911-1914)",
        "name_pt": "A Ferrovia Berlim-Bagdá & Influência Sublime",
        "sprite": "GFX_focus_GER_berlin_baghdad_railway",
        "dds_name": "focus_GER_berlin_baghdad_railway.dds",
        "source_path": os.path.join(base_ws, "GFX_TUR_baghdadberlin_railway-86221.dds"),
        "visual_desc": "Locomotiva a vapor alemã cruzando o deserto sob aliança otomana",
        "is_source_dds": True,
    },
    {
        "focus_id": "GER_army_bill_1912",
        "phase": "Phase I (1911-1914)",
        "name_pt": "A Lei Militar de 1912 (Heeresvorlage)",
        "sprite": "GFX_focus_GER_army_bill_1912",
        "dds_name": "focus_GER_army_bill_1912.dds",
        "source_path": os.path.join(base_ws, "GFX_GER_militarism-86387.dds"),
        "visual_desc": "Capacete Pickelhaube e sabres da infantaria prussiana",
        "is_source_dds": True,
    },
    {
        "focus_id": "GER_centenary_of_leipzig_1913",
        "phase": "Phase I (1911-1914)",
        "name_pt": "O Jubileu de Prata do Kaiser & Leipzig 1913",
        "sprite": "GFX_focus_GER_centenary_of_leipzig_1913",
        "dds_name": "focus_GER_centenary_of_leipzig_1913.dds",
        "source_path": os.path.join(base_ws, "hoi4tgw", "ww1_nationalfocus_germanempire.dds"),
        "visual_desc": "Coroa Imperial Alemã do Segundo Reich com louros e águia",
        "is_source_dds": True,
    },
    {
        "focus_id": "GER_expand_heavy_howitzers",
        "phase": "Phase I (1911-1914)",
        "name_pt": "Os Obuses de Cerco Krupp de 420mm (Dicke Bertha)",
        "sprite": "GFX_focus_GER_krupp",
        "dds_name": "focus_GER_krupp.dds",
        "source_path": os.path.join(base_ws, "GER", "focus_GER_krupp.png"),
        "visual_desc": "Forja dos canhões Krupp e obuses pesados de cerco",
        "is_source_dds": False,
    },
    {
        "focus_id": "GER_the_blank_cheque",
        "phase": "Phase I (1911-1914)",
        "name_pt": "O Cheque em Branco a Viena (Julho de 1914)",
        "sprite": "GFX_focus_ger_support_austrian_claims",
        "dds_name": "focus_ger_support_austrian_claims.dds",
        "source_path": os.path.join(base_ws, "GER", "focus_ger_support_austrian_claims.png"),
        "visual_desc": "Águia Imperial Alemã e Águia Bicéfala Austro-Húngara unidas",
        "is_source_dds": False,
    },

    # Phase II (1914-1917)
    {
        "focus_id": "GER_execute_schlieffen_plan",
        "phase": "Phase II (1914-1917) - Schlieffen",
        "name_pt": "Executar o Plano Schlieffen",
        "sprite": "GFX_focus_ger_around_maginot",
        "dds_name": "focus_ger_around_maginot.dds",
        "source_path": os.path.join(base_ws, "GER", "focus_ger_around_maginot.png"),
        "visual_desc": "Flecha em foice contornando fortes pela Bélgica em direção a Paris",
        "is_source_dds": False,
    },
    {
        "focus_id": "GER_smash_liege_forts",
        "phase": "Phase II (1914-1917) - Schlieffen",
        "name_pt": "A Queda dos Fortes de Liège",
        "sprite": "GFX_ww1_mex_upca_conquer",
        "dds_name": "ww1_mex_upca_conquer.dds",
        "source_path": os.path.join(base_ws, "hoi4tgw", "ww1_mex_upca_conquer.dds"),
        "visual_desc": "Explosão de artilharia pesada estilhaçando fortes e cúpulas blindadas",
        "is_source_dds": True,
    },
    {
        "focus_id": "GER_the_miracle_of_tannenberg",
        "phase": "Phase II (1914-1917) - Schlieffen",
        "name_pt": "O Triunfo de Tannenberg no Leste",
        "sprite": "GFX_focus_GER_the_miracle_of_tannenberg",
        "dds_name": "focus_GER_the_miracle_of_tannenberg.dds",
        "source_path": os.path.join(base_ws, "GFX_GER_auftragstaktik-69190.dds"),
        "visual_desc": "Estado-Maior prussiano e ruptura de manobra nos Lagos Masurianos",
        "is_source_dds": True,
    },
    {
        "focus_id": "GER_aufmarsch_ost_focus",
        "phase": "Phase II (1914-1917) - Aufmarsch Ost",
        "name_pt": "Aufmarsch II Ost: Esmagar a Rússia Primeiro",
        "sprite": "GFX_focus_GER_aufmarsch_ost_focus",
        "dds_name": "focus_GER_aufmarsch_ost_focus.dds",
        "source_path": os.path.join(base_ws, "hoi4tgw", "ww1_nationalfocus_russianempire.dds"),
        "visual_desc": "Espadas germânicas cruzadas sobre a águia czarista oriental",
        "is_source_dds": True,
    },
    {
        "focus_id": "GER_haber_bosch_nitrogen_miracle",
        "phase": "Phase II (1914-1917) - Guerra Total",
        "name_pt": "O Milagre Químico de Fritz Haber (Fixação de Nitrogênio)",
        "sprite": "GFX_focus_GER_haber_bosch_nitrogen_miracle",
        "dds_name": "focus_GER_haber_bosch_nitrogen_miracle.dds",
        "source_path": os.path.join(base_ws, "GFX_GER_chemical_industry_expansion-73665.dds"),
        "visual_desc": "Complexo químico industrial e retortas de síntese de amônia",
        "is_source_dds": True,
    },
    {
        "focus_id": "GER_chemical_warfare_initiative",
        "phase": "Phase II (1914-1917) - Guerra Total",
        "name_pt": "A Nuvem Amarela em Ypres (Guerra com Cloro e Gás Mostarda)",
        "sprite": "GFX_ww1_nationalfocus_gasmask",
        "dds_name": "ww1_nationalfocus_gasmask.dds",
        "source_path": os.path.join(base_ws, "hoi4tgw", "ww1_nationalfocus_gasmask.dds"),
        "visual_desc": "Soldado nas trincheiras usando máscara de gás M15 entre névoa química",
        "is_source_dds": True,
    },
    {
        "focus_id": "GER_hindenburg_program",
        "phase": "Phase II (1914-1917) - Guerra Total",
        "name_pt": "O Programa Hindenburg de Guerra Total (1916)",
        "sprite": "GFX_focus_OHL",
        "dds_name": "focus_OHL.dds",
        "source_path": os.path.join(base_ws, "GER", "focus_OHL.png"),
        "visual_desc": "Brasão oficial da Oberste Heeresleitung e comando supremo",
        "is_source_dds": False,
    },
    {
        "focus_id": "GER_stosstruppen_tactics",
        "phase": "Phase II (1914-1917) - Guerra Total",
        "name_pt": "A Gênese das Tropas de Tempestade (Stosstruppen)",
        "sprite": "GFX_ww1_nationalfocus_ironcross",
        "dds_name": "ww1_nationalfocus_ironcross.dds",
        "source_path": os.path.join(base_ws, "hoi4tgw", "ww1_nationalfocus_ironcross.dds"),
        "visual_desc": "Cruz de Ferro negra sobre Stahlhelm de choque e granadas de bastão",
        "is_source_dds": True,
    },

    # Phase III (1917-1920+) - Rota 1: OHL
    {
        "focus_id": "GER_silent_dictatorship_ohl",
        "phase": "Phase III - Ditadura OHL",
        "name_pt": "A Proclamação da OHL de Hindenburg e Ludendorff",
        "sprite": "GFX_focus_GER_silent_dictatorship_ohl",
        "dds_name": "focus_GER_silent_dictatorship_ohl.dds",
        "source_path": os.path.join(base_ws, "GFX_GER_military_dictatorship-86217.dds"),
        "visual_desc": "Espada e coroa militar sob ditadura castrense da OHL",
        "is_source_dds": True,
    },
    {
        "focus_id": "GER_unrestricted_submarine_warfare",
        "phase": "Phase III - Ditadura OHL",
        "name_pt": "Guerra Submarina Irrestrita Total",
        "sprite": "GFX_focus_GER_unrestricted_submarine_warfare",
        "dds_name": "focus_GER_unrestricted_submarine_warfare.dds",
        "source_path": os.path.join(base_ws, "GER", "focus_kriegsmarine.png"),
        "visual_desc": "Periscópio e silhueta de U-Boot torpedeando navios mercantes",
        "is_source_dds": False,
    },
    {
        "focus_id": "GER_sealed_train_to_petrograd",
        "phase": "Phase III - Ditadura OHL",
        "name_pt": "O Vagão Selado Para Petrogrado (O Retorno de Lenin)",
        "sprite": "GFX_focus_GER_sealed_train_to_petrograd",
        "dds_name": "focus_GER_sealed_train_to_petrograd.dds",
        "source_path": os.path.join(base_ws, "generic", "focus_generic_train.png"),
        "visual_desc": "Vagão blindado e trem expresso acelerando em direção à fronteira russa",
        "is_source_dds": False,
    },
    {
        "focus_id": "GER_treaty_of_brest_litovsk",
        "phase": "Phase III - Ditadura OHL",
        "name_pt": "A Paz de Brest-Litovsk (Março de 1918)",
        "sprite": "GFX_goal_deal_with_german_empire",
        "dds_name": "focus_deal_with_german_empire.dds",
        "source_path": os.path.join(base_ws, "GER", "focus_deal_with_german_empire.png"),
        "visual_desc": "Pena de ouro assinando os mapas da partilha territorial do Leste",
        "is_source_dds": False,
    },
    {
        "focus_id": "GER_the_kaiserschlacht_1918",
        "phase": "Phase III - Ditadura OHL",
        "name_pt": "A Ofensiva Imperial Final da Primavera (Kaiserschlacht)",
        "sprite": "GFX_focus_GER_the_kaiserschlacht_1918",
        "dds_name": "focus_GER_the_kaiserschlacht_1918.dds",
        "source_path": os.path.join(base_ws, "GFX_GER_sturmtruppen-86215.dds"),
        "visual_desc": "Assalto frontal de infantaria com lança-chamas e capacetes Stahlhelm",
        "is_source_dds": True,
    },

    # Phase III - Rota 2: Volkskaiserreich
    {
        "focus_id": "GER_bethmann_civilian_supremacy",
        "phase": "Phase III - Volkskaiserreich",
        "name_pt": "A Supremacia da Chancelaria Civil sobre a OHL",
        "sprite": "GFX_focus_GER_bethmann_civilian_supremacy",
        "dds_name": "focus_GER_bethmann_civilian_supremacy.dds",
        "source_path": os.path.join(base_ws, "generic", "royal_prerogatives.png"),
        "visual_desc": "Decreto imperial selado e subordinação civil da liderança bélica",
        "is_source_dds": False,
    },
    {
        "focus_id": "GER_prussian_franchise_reform",
        "phase": "Phase III - Volkskaiserreich",
        "name_pt": "Abolição do Voto Prussiano de Três Classes",
        "sprite": "GFX_focus_GER_prussian_franchise_reform",
        "dds_name": "focus_GER_prussian_franchise_reform.dds",
        "source_path": os.path.join(base_ws, "generic", "goal_generic_socdem.png"),
        "visual_desc": "Rosa social-democrata e urna eleitoral de sufrágio universal igualitário",
        "is_source_dds": False,
    },
    {
        "focus_id": "GER_reichstag_peace_resolution",
        "phase": "Phase III - Volkskaiserreich",
        "name_pt": "A Resolução de Paz do Reichstag de Julho de 1917",
        "sprite": "GFX_focus_GER_reichstag_peace_resolution",
        "dds_name": "focus_GER_reichstag_peace_resolution.dds",
        "source_path": os.path.join(base_ws, "GER", "expanded_duty.png"),
        "visual_desc": "Manifesto do parlamento imperial por uma paz de entendimento sem anexações",
        "is_source_dds": False,
    },
    {
        "focus_id": "GER_constitutional_monarchy_proclamation",
        "phase": "Phase III - Volkskaiserreich",
        "name_pt": "A Proclamação da Monarquia Parlamentar",
        "sprite": "GFX_focus_GER_constitutional_monarchy_proclamation",
        "dds_name": "focus_GER_constitutional_monarchy_proclamation.dds",
        "source_path": os.path.join(base_ws, "generic", "goal_royal_edicts2.png"),
        "visual_desc": "Coroa constitucional prussiana sob carta magna e leis fundamentais",
        "is_source_dds": False,
    },

    # Phase III - Rota 3: Vaterlandspartei
    {
        "focus_id": "GER_found_vaterlandspartei",
        "phase": "Phase III - Vaterlandspartei",
        "name_pt": "A Fundação do Partido da Pátria Alemã (1917)",
        "sprite": "GFX_focus_GER_found_vaterlandspartei",
        "dds_name": "focus_GER_found_vaterlandspartei.dds",
        "source_path": os.path.join(base_ws, "GFX_GER_mllitary_leagues_demands-86384.dds"),
        "visual_desc": "Estandarte nacionalista radical da Vaterlandspartei de Tirpitz e Kapp",
        "is_source_dds": True,
    },
    {
        "focus_id": "GER_total_war_mobilization",
        "phase": "Phase III - Vaterlandspartei",
        "name_pt": "Mobilização da Força de Trabalho Feminina e Compulsória",
        "sprite": "GFX_focus_GER_total_war_mobilization",
        "dds_name": "focus_GER_total_war_mobilization.dds",
        "source_path": os.path.join(base_ws, "GFX_GER_auxiliary_service_law-87477.dds"),
        "visual_desc": "Engrenagens industriais sob a Lei do Serviço Auxiliar Patriótico",
        "is_source_dds": True,
    },
    {
        "focus_id": "GER_annexation_of_belgium_and_briey",
        "phase": "Phase III - Vaterlandspartei",
        "name_pt": "A Anexação Permanente da Bélgica e Bacia de Briey",
        "sprite": "GFX_focus_GER_annexation_of_belgium_and_briey",
        "dds_name": "focus_GER_annexation_of_belgium_and_briey.dds",
        "source_path": os.path.join(base_ws, "generic", "second_belgian_award.png"),
        "visual_desc": "Divisão e anexação imperial da bacia de ferro de Briey e Flandres",
        "is_source_dds": False,
    },
    {
        "focus_id": "GER_morphed_mitteleuropa_iron_rule",
        "phase": "Phase III - Vaterlandspartei",
        "name_pt": "A Mitteleuropa sob o Tacão de Ferro",
        "sprite": "GFX_focus_GER_morphed_mitteleuropa_iron_rule",
        "dds_name": "focus_GER_morphed_mitteleuropa_iron_rule.dds",
        "source_path": os.path.join(base_ws, "GFX_GER_consolidate_central_powers-86219.dds"),
        "visual_desc": "Poderes Centrais unidos sob a hegemonia militar de Berlim",
        "is_source_dds": True,
    },

    # Easter Eggs & Alt-History
    {
        "focus_id": "GER_willy_nicky_telegrams_bjorko",
        "phase": "Easter Eggs & Alt-History",
        "name_pt": "Os Telegramas de Willy e Nicky (Björkö 2.0)",
        "sprite": "GFX_focus_GER_willy_nicky_telegrams_bjorko",
        "dds_name": "focus_GER_willy_nicky_telegrams_bjorko.dds",
        "source_path": os.path.join(base_ws, "generic", "focus_deal_with_russia.png"),
        "visual_desc": "Aperto de mão e pacto secreto imperial entre o Kaiser e o Czar",
        "is_source_dds": False,
    },
    {
        "focus_id": "GER_hajj_wilhelm_pan_islamic_crusade",
        "phase": "Easter Eggs & Alt-History",
        "name_pt": "A Proclamação da Guerra Santa Imperial (Hajj Wilhelm)",
        "sprite": "GFX_ww1_nationalfocus_islam",
        "dds_name": "ww1_nationalfocus_islam.dds",
        "source_path": os.path.join(base_ws, "hoi4tgw", "ww1_nationalfocus_islam.dds"),
        "visual_desc": "Crescente islâmico dourado ladeado pela coroa e águia imperial alemã",
        "is_source_dds": True,
    },
    {
        "focus_id": "GER_spartakusbund_proletarian_revolt",
        "phase": "Easter Eggs & Alt-History",
        "name_pt": "A Revolta dos Espartaquistas de Berlim (1917)",
        "sprite": "GFX_goal_generic_workers",
        "dds_name": "focus_socialist_worker.dds",
        "source_path": os.path.join(base_ws, "generic", "focus_socialist_worker.png"),
        "visual_desc": "Proletariado em armas e bandeira vermelha da Liga Espartaquista",
        "is_source_dds": False,
    },
    {
        "focus_id": "GER_emergency_danubian_annexation",
        "phase": "Easter Eggs & Alt-History",
        "name_pt": "A Intervenção de Emergência nos Territórios Habsburgos (Großdeutschland)",
        "sprite": "GFX_focus_GER_emergency_danubian_annexation",
        "dds_name": "focus_GER_emergency_danubian_annexation.dds",
        "source_path": os.path.join(base_ws, "hoi4tgw", "ww1_nationalfocus_austriahungary.dds"),
        "visual_desc": "Águia dos Habsburgos absorvida na coroa imperial pangermânica",
        "is_source_dds": True,
    },
]

print("Testing Pillow conversion & validation on all 32 files...")
converted_count = 0
for item in focus_mapping:
    src = item["source_path"]
    im = Image.open(src)
    if im.mode != "RGBA":
        im = im.convert("RGBA")
    
    # Save to memory buffer as DDS to verify Pillow export capability
    buf = io.BytesIO()
    im.save(buf, format="DDS")
    buf_size = buf.tell()
    assert buf_size > 0, f"Empty buffer for {src}"
    converted_count += 1

print(f"Successfully validated all {converted_count} files via Pillow in-memory DDS encoding!")
