"""Generates scripts/ita_support_loc.py containing bilingual dictionaries
for all decision categories, decisions, ideas, opinion modifiers, and events.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Support dictionaries
SUPPORT_PT = {}
SUPPORT_EN = {}

def add(k, pt, en):
    SUPPORT_PT[k] = pt
    SUPPORT_EN[k] = en

# Categories
add("ITA_ww1_internal_politics_category", "Política Interna e Sociedade", "Internal Politics & Society")
add("ITA_ww1_internal_politics_category_desc", "Gestão de reformas sociais e tensões civis.", "Management of social reforms and civil tension.")
add("ITA_ww1_diplomatic_initiatives_category", "Iniciativas Diplomáticas", "Diplomatic Initiatives")
add("ITA_ww1_diplomatic_initiatives_category_desc", "Condução das relações exteriores e acordos de compensação.", "Conduct of foreign relations and compensation accords.")
add("ITA_ww1_economic_mobilisation_category", "Mobilização Econômica", "Economic Mobilisation")
add("ITA_ww1_economic_mobilisation_category_desc", "Desenvolvimento do Mezzogiorno e produção bélica.", "Mezzogiorno development and war production.")
add("ITA_ww1_military_readiness_category", "Prontidão Militar e Naval", "Military & Naval Readiness")
add("ITA_ww1_military_readiness_category_desc", "Preparação do Regio Esercito e da Regia Marina.", "Preparation of the Regio Esercito and Regia Marina.")

# Decisions
decisions = [
    ("grant_universal_suffrage_amnesty", "Conceder anistia eleitoral", "Grant Universal Suffrage Amnesty", "Alivia a tensão civil perdoando infrações eleitorais menores.", "Relieves civil tension by pardoning minor electoral infractions."),
    ("contain_socialist_agitation", "Conter a agitação socialista", "Contain Socialist Agitation", "Medidas policiais focadas em líderes grevistas radicais.", "Focused police measures targeting radical strike leaders."),
    ("subsidise_catholic_schools", "Subsidiar escolas católicas", "Subsidise Catholic Schools", "Fortalece a cooperação com eleitores católicos moderados.", "Strengthens cooperation with moderate Catholic voters."),
    ("emergency_police_decrees", "Decretos policiais de emergência", "Emergency Police Decrees", "Poderes extraordinários para garantir a ordem interna em tempo de guerra.", "Extraordinary powers to secure wartime internal order."),
    ("repress_squadrist_violence", "Reprimir a violência dos esquadrões", "Repress Squadrist Violence", "Desarmar milícias e bandos armados ilegais.", "Disarm illegal armed squads and militias."),
    ("negotiate_factory_arbitration", "Negociar arbitragem fabril", "Negotiate Factory Arbitration", "Mediação entre sindicatos e industriais para evitar paralisações.", "Mediation between unions and industrialists to avert stoppages."),
    ("diplomatic_pressure_tripoli", "Pressionar pela cessão de Trípoli", "Diplomatic Pressure on Tripoli", "Envio de nota formal à Sublime Porta propondo acordo sobre a Líbia.", "Dispatch formal diplomatic terms to the Porte proposing a Libyan accord."),
    ("adriatic_naval_patrols", "Patrulhas navais no Adriático", "Adriatic Naval Patrols", "Demonstração de força naval entre Brindisi e Veneza.", "Naval demonstration between Brindisi and Venice."),
    ("reassure_berlin_and_vienna", "Reafirmar lealdade aos aliados centrais", "Reassure Berlin and Vienna", "Consultas diplomáticas para preservar a Tríplice Aliança.", "Diplomatic talks to preserve the Triple Alliance."),
    ("secret_contacts_with_paris", "Contatos secretos com Paris", "Secret Contacts with Paris", "Sondagens discretas com o Ministério dos Negócios Estrangeiros francês.", "Discreet soundings with the French Foreign Ministry."),
    ("vatican_reconciliation_talks", "Diálogo conciliatório com a Santa Sé", "Vatican Reconciliation Talks", "Aproximação institucional entre o Estado italiano e a Igreja.", "Institutional rapprochement between the Italian State and the Church."),
    ("oppressed_nationalities_liaison", "Apoio às nacionalidades oprimidas", "Oppressed Nationalities Liaison", "Contatos com comitês tchecos e eslavos do sul.", "Liaison with Czech and South Slav national committees."),
    ("expand_ansaldo_artillery_works", "Ampliar oficinas bélicas da Ansaldo", "Expand Ansaldo Artillery Works", "Investimento em linhas de montagem de canhões em Gênova.", "Capital investment in artillery assembly lines in Genoa."),
    ("fiat_lorry_expansion", "Ampliar linhas de montagem da FIAT", "FIAT Lorry Expansion", "Produção em série de caminhões militares em Turim.", "Mass production of military trucks in Turin."),
    ("alpine_hydroelectric_dam", "Construir barragem hidrelétrica alpina", "Alpine Hydroelectric Dam", "Geração de energia elétrica para a indústria lombarda.", "Electrical generation for Lombard industrial plants."),
    ("apulian_aqueduct_expansion", "Ampliar o aqueduto da Apúlia", "Apulian Aqueduct Expansion", "Canalização de água potável para cidades meridionais.", "Canalisation of drinking water to southern towns."),
    ("mezzogiorno_grain_subsidies", "Subsídios ao trigo do Mezzogiorno", "Mezzogiorno Grain Subsidies", "Crédito agrário para pequenos produtores do Sul.", "Agrarian credit for southern smallholders."),
    ("ration_civilian_coal", "Racionar carvão civil", "Ration Civilian Coal", "Priorizar carvão para altos-fornos e ferrovias militares.", "Prioritize coal for blast furnaces and military railways."),
    ("train_alpini_mountain_battalions", "Treinar batalhões alpinos", "Train Alpini Mountain Battalions", "Instrução avançada em geleiras e paredões rochosos.", "Advanced training on glaciers and rock walls."),
    ("arditi_assault_schools", "Escolas de assalto dos Arditi", "Arditi Assault Schools", "Formação intensiva em combate corpo a corpo e infiltração.", "Intensive training in hand-to-hand combat and infiltration."),
    ("fortify_carso_plateau", "Fortificar o planalto do Carso", "Fortify Carso Plateau", "Escarpações rochosas e cavernas defensivas em Friul.", "Rock scarps and defensive caverns in Friuli."),
    ("expand_taranto_naval_arsenal", "Ampliar o arsenal naval de Taranto", "Expand Taranto Naval Arsenal", "Diques secos adicionais para reparos de couraçados.", "Additional dry docks for dreadnought repairs."),
    ("commission_caproni_heavy_bombers", "Encomendar bombardeiros pesados Caproni", "Commission Caproni Heavy Bombers", "Acelerar a entrega de trimotores de bombardeio.", "Accelerate delivery of three-engine bombers."),
    ("mas_stealth_patrols", "Patrulhas de lanchas MAS", "MAS Stealth Patrols", "Incursões rápidas com torpedos ao longo da costa adriática.", "Rapid torpedo incursions along the Adriatic coast."),
    ("propaganda_trench_newspapers", "Publicar jornais de trincheira", "Propaganda Trench Newspapers", "Ilustrações patrióticas para manter o ânimo dos soldados.", "Patriotic illustrations to bolster soldier morale."),
    ("veteran_resettlement_parcels", "Lotes rurais para veteranos", "Veteran Resettlement Parcels", "Concessão de terras agrícolas a ex-combatentes.", "Allotment of agricultural land to ex-combatants.")
]

for did, pt, en, dpt, den in decisions:
    full_did = f"ITA_ww1_{did}"
    add(full_did, pt, en)
    add(f"{full_did}_desc", dpt, den)

# Ideas
ideas = [
    ("neutralist_predominance", "Predomínio Neutralista", "Neutralist Predominance", "A maioria do parlamento e da população favorece a paz e a neutralidade.", "The majority of parliament and the public favors peace and neutrality."),
    ("divided_public_opinion", "Opinião Pública Dividida", "Divided Public Opinion", "O país está dividido entre neutralistas moderados e comícios intervencionistas.", "The country is split between moderate neutralists and interventionist rallies."),
    ("radiant_fever", "Febre Intervencionista", "Radiant Fever", "As multidões patrióticas dominam as praças exigindo a guerra de libertação.", "Patriotic crowds dominate public squares demanding the war of liberation."),
    ("social_truce", "Trégua Social", "Social Truce", "Acordos entre capital e trabalho asseguram paz social e produtividade.", "Agreements between capital and labor secure social peace and productivity."),
    ("labour_friction", "Atrito Trabalhista", "Labour Friction", "Tensões salariais e greves esporádicas afetam o ritmo fabril.", "Wage disputes and sporadic strikes affect factory throughput."),
    ("revolutionary_ferment", "Fermento Revolucionário", "Revolutionary Ferment", "Greves massivas e agitação maximalista paralisam cidades industriais.", "Mass strikes and maximalist agitation paralyze industrial cities."),
    ("shattered_discipline", "Disciplina Abalada", "Shattered Discipline", "O choque das derrotas e a exaustão militar abalam as fileiras do exército.", "The shock of defeats and military exhaustion shake the army's ranks."),
    ("stoic_endurance", "Resistência Estoica", "Stoic Endurance", "Os soldados suportam privações extremas nas montanhas e trincheiras.", "Soldiers endure extreme hardship in the mountains and trenches."),
    ("victorious_ardor", "Ardor Vitorioso", "Victorious Ardor", "O entusiasmo de vitórias recentes eleva a moral e a confiança na liderança.", "The enthusiasm of recent victories boosts morale and faith in command."),
    ("integrated_mezzogiorno", "Mezzogiorno Integrado", "Integrated Mezzogiorno", "Investimentos e obras públicas reduzem o fosso histórico entre Norte e Sul.", "Investments and public works narrow the historic gap between North and South."),
    ("southern_disparity", "Disparidade Meridional", "Southern Disparity", "A falta de infraestrutura e a emigração pesam sobre as regiões do Sul.", "Lack of infrastructure and emigration weigh heavily upon southern regions."),
    ("acute_agrarian_crisis", "Crise Agrária Aguda", "Acute Agrarian Crisis", "Carestia no campo e êxodo populacional desestruturam a economia rural.", "Rural scarcity and population exodus disrupt the rural economy."),
    ("subdued_claims", "Reivindicações Contidas", "Subdued Claims", "A diplomacia busca acomodação pacífica e preservação do comércio marítimo.", "Diplomacy seeks peaceful accommodation and maritime trade preservation."),
    ("unredeemed_lands_call", "O Chamado das Terras Irredentas", "Call of the Unredeemed Lands", "A causa de Trento e Trieste ganha força nos debates políticos.", "The cause of Trent and Trieste gains momentum in political debate."),
    ("irredentist_fervor", "Fervor Irredentista", "Irredentist Fervor", "Exigências intransigentes por todas as terras históricas dominam o debate nacional.", "Uncompromising demands for all historic lands dominate national discourse."),
    ("trasformismo_politics", "Prática do Trasformismo", "Trasformismo Politics", "O sistema político é governado por negociações contínuas entre bancadas.", "The political system is governed by continuous cross-faction compromise."),
    ("universal_suffrage", "Sufrágio Universal Masculino", "Universal Male Suffrage", "O direito de voto ampliado incorpora milhões de camponeses e operários à vida cívica.", "Expanded franchise incorporates millions of peasants and workers into civic life."),
    ("gentiloni_compact", "Pacto Gentiloni", "Gentiloni Compact", "Acordo eleitoral com os católicos fortalece a estabilidade contra correntes radicais.", "Electoral accord with Catholics strengthens stability against radical currents."),
    ("red_week_aftermath", "Rescaldo da Semana Vermelha", "Red Week Aftermath", "Tensões sociais e desconfiança policial permanecem elevadas após os motins.", "Social tension and police distrust remain heightened following riots."),
    ("radiant_may_fervor", "Entusiasmo do Maio Radiante", "Radiant May Fervor", "Mobilização popular entusiástica pela causa da libertação nacional.", "Enthusiastic popular mobilization for the cause of national liberation."),
    ("sacro_egoismo", "Doutrina do Sacro Egoismo", "Sacro Egoismo Doctrine", "Defesa incondicional do interesse geopolítico italiano acima de pactos externos.", "Unconditional defense of Italian geopolitical interest above external pacts."),
    ("mutilated_victory_syndrome", "Sentimento de Vitória Mutilada", "Mutilated Victory Syndrome", "Rancor pelo não cumprimento integral do Pacto de Londres em Versalhes.", "Resentment over incomplete fulfillment of the London Pact at Versailles."),
    ("biennio_rosso_strikes", "Agitação do Biênio Vermelho", "Biennio Rosso Strikes", "Ocupações fabris e greves rurais desestabilizam o tecido social do país.", "Factory occupations and agrarian strikes destabilize the nation's social fabric."),
    ("squadrist_violence", "Violência dos Esquadrões", "Squadrist Violence", "Expedições punitivas de camisas-negras aterrorizam organizações de esquerda.", "Blackshirt punitive expeditions terrorize left-wing organizations."),
    ("pci_workers_councils", "Conselhos Operários de Fábrica", "Workers' Factory Councils", "Operários assumem a gestão direta da produção nas indústrias ocupadas.", "Workers take direct control of production management in occupied plants."),
    ("opera_nazionale_combattenti", "Opera Nazionale Combattenti", "Opera Nazionale Combattenti", "Instituição estatal de assistência e integração social de veteranos.", "State welfare institution for veteran assistance and reintegration."),
    ("propaganda_service_spirit", "Servizio P de Moral Militar", "Servizio P Troop Morale", "Propaganda ativa e jornais ilustrados sustentam o espírito das tropas.", "Active propaganda and illustrated gazettes sustain the troops' spirit."),
    ("salandra_emergency_cabinet", "Gabinete de Crise de Salandra", "Salandra Emergency Cabinet", "Liderança conservadora focada na prontidão e na intervenção armada.", "Conservative leadership focused on military readiness and armed intervention."),
    ("orlando_victory_cabinet", "Gabinete de Resistência de Orlando", "Orlando National Resistance Cabinet", "Governo de determinação nacional para a vitória definitiva na Grande Guerra.", "National determination government for final victory in the Great War.")
]

for iid, pt, en, dpt, den in ideas:
    full_iid = f"ITA_ww1_{iid}"
    add(full_iid, pt, en)
    add(f"{full_iid}_desc", dpt, den)

# Opinion modifiers
opinions = [
    ("sacro_egoismo_suspicion", "Suspeita por 'Sacro Egoismo'", "Suspicion over 'Sacro Egoismo'"),
    ("gentiloni_reconciliation", "Reconciliação Católica", "Catholic Reconciliation"),
    ("treaty_of_london_solidarity", "Solidariedade do Tratado de Londres", "Treaty of London Solidarity"),
    ("central_powers_betrayal", "Traição da Tríplice Aliança", "Triple Alliance Betrayal"),
    ("adriatic_dispute", "Disputa no Adriático", "Adriatic Dispute"),
    ("albanian_influence_rivalry", "Rivalidade sobre a Albânia", "Rivalry over Albania"),
    ("latin_sisterhood", "Fraternidade Latina", "Latin Sisterhood"),
    ("mediterranean_naval_cooperation", "Cooperação Naval Mediterrânea", "Mediterranean Naval Cooperation")
]

for oid, pt, en in opinions:
    add(f"ITA_ww1_{oid}", pt, en)

# Events 1 to 78
event_titles = {
    1: ("A Reforma Eleitoral de 1912", "The Electoral Reform of 1912", "A ampliação do sufrágio masculino altera o equilíbrio das forças políticas.", "The expansion of male suffrage alters the balance of political forces.", "Aprovar a reforma abrangente.", "Enact the comprehensive reform.", "Limitar as concessões à alfabetização.", "Restrict concessions to literate voters."),
    2: ("O Instituto Nacional de Seguros", "The National Insurance Institute", "A criação do INA consolida a previdência e o crédito público.", "The foundation of INA consolidates public pensions and state credit.", "Instituir o monopólio público.", "Establish the public monopoly.", "Permitir consórcios privados.", "Permit private consortia."),
    3: ("O Congresso Nacionalista de Florença", "The Nationalist Congress in Florence", "A fundação da ANI proclama a necessidade de expansão colonial.", "The ANI congress proclaims the imperative of imperial expansion.", "Acolher o fervor patriótico.", "Welcome patriotic fervor.", "Repudiar a retórica belicista.", "Repudiate belligerent rhetoric."),
    4: ("Congresso Socialista de Reggio Emilia", "Congress of Reggio Emilia", "Os maximalistas tomam o controle do partido socialista.", "Maximalists seize control of the Italian Socialist Party.", "Observar as resoluções com cautela.", "Observe the resolutions with caution.", "Intensificar a vigilância policial.", "Intensify police surveillance."),
    5: ("O Pacto Gentiloni", "The Gentiloni Pact", "Candidatos liberais selam aliança silenciosa com o eleitorado católico.", "Liberal candidates seal a quiet compact with the Catholic electorate.", "Ratificar os acordos com a Santa Sé.", "Ratify understandings with the Holy See.", "Preservar estrita laicidade estatal.", "Preserve strict state secularism."),
    6: ("Ação Social Católica no Campo", "Catholic Social Action", "Bancos rurais e cooperativas apoiam o campesinato italiano.", "Rural banks and peasant cooperatives sustain the Italian countryside.", "Apoiar as ligas camponesas.", "Support peasant leagues.", "Manter neutralidade administrativa.", "Maintain administrative neutrality."),
    7: ("A Semana Vermelha de 1914", "Red Week of 1914", "Motins populares e greves gerais espalham-se pela Romagna e Marcas.", "Popular riots and general strikes erupt across Romagna and the Marches.", "Restaurar a ordem pública com firmeza.", "Restore public order firmly.", "Evitar confrontos diretos nas ruas.", "Avoid direct clashes in the streets."),
    8: ("Restauração da Ordem Civil", "Restoration of Public Order", "As tropas governamentais restabelecem a tranquilidade no país.", "Government troops re-establish tranquility across the country.", "Ordem restaurada sem excessos.", "Order restored without excesses.", "Conceder anistia a manifestantes.", "Grant amnesty to protestors."),
    9: ("O Gabinete Salandra Assume", "Salandra Takes Office", "Antonio Salandra assume o governo em meio a tensões crescentes.", "Antonio Salandra assumes leadership amidst mounting tensions.", "Apoiar a linha governamental firme.", "Support firm government leadership.", "Manter fiscalização parlamentar.", "Maintain parliamentary oversight."),
    10: ("Fundação de Il Popolo d'Italia", "Il Popolo d'Italia Founded", "Mussolini rompe com a neutralidade socialista e funda novo jornal.", "Mussolini breaks with socialist neutrality and launches a new daily.", "Apoiar a agitação intervencionista.", "Support interventionist agitation.", "Ignorar a nova publicação.", "Ignore the new publication."),
    11: ("O Discurso de Quarto", "The Quarto Speech", "Gabriele D'Annunzio conclama o povo italiano à guerra sagrada.", "Gabriele D'Annunzio calls the Italian people to holy war.", "Ouvir a conclamação da pátria!", "Heed the call of the fatherland!", "Conter os excessos patrióticos.", "Restrain patriotic excesses."),
    12: ("O 'Parecchio' de Giolitti", "Giolitti's 'Parecchio'", "Giolitti propõe obter compensações austríacas sem derramamento de sangue.", "Giolitti proposes securing Austrian concessions without bloodshed.", "Negociar concessões com Viena.", "Negotiate concessions with Vienna.", "A hora da diplomacia já passou!", "The hour of diplomacy has passed!"),
    13: ("O Maio Radiante", "The Radiant May", "Multidões em fúria tomam Roma e Milão forçando a entrada na guerra.", "Impassioned crowds seize Rome and Milan demanding entry into war.", "Avanti, Itália! Pela guerra de libertação!", "Forward, Italy! For the war of liberation!", "Tentar acalmar os ânimos nas praças.", "Attempt to calm tempers in the squares."),
    14: ("Censura de Imprensa em Tempo de Guerra", "Wartime Press Censorship", "Decretos de emergência limitam notícias do fronte e críticas ao comando.", "Emergency decrees restrict front-line reports and criticisms of command.", "Aplicar censura preventiva total.", "Enforce total preventive censorship.", "Permitir debates moderados.", "Permit moderate debates."),
    15: ("O Gabinete de União de Boselli", "Boselli's National Unity Cabinet", "Paolo Boselli assume para liderar um ministério de consenso patriótico.", "Paolo Boselli assumes leadership of a patriotic coalition cabinet.", "Unir todas as correntes nacionais.", "Unite all national currents.", "Priorizar eficiência técnica.", "Prioritize technical efficiency."),
    16: ("Mulheres na Mobilização Fabril", "Women in Industrial Mobilisation", "Milhares de trabalhadoras assumem postos nas fábricas de armamento.", "Thousands of female workers take positions in munitions plants.", "Expandir creches e assistência operária.", "Expand childcare and worker assistance.", "Manter contratos temporários.", "Maintain temporary contracts."),
    17: ("O Servizio P de Moral Militar", "Servizio P Soldier Morale", "Campanhas culturais e jornais ilustrados animam as trincheiras.", "Cultural campaigns and illustrated gazettes encourage the trenches.", "Investir na moral dos infantes.", "Invest in the infantry's morale.", "Redirecionar fundos para munições.", "Redirect funds to munitions."),
    18: ("A Promessa de Terra aos Soldados", "Promise of Land to Peasant-Soldiers", "O governo garante lotes rurais aos combatentes após a vitória.", "The government pledges rural parcels to soldiers after victory.", "Renovar solenemente o compromisso.", "Solemnly renew the pledge.", "Focar nas exigências imediatas.", "Focus on immediate demands."),
    19: ("Comissão de Inquérito de Caporetto", "Caporetto Commission of Inquiry", "O parlamento investiga as causas militares do desastre no Isonzo.", "Parliament investigates the military causes of the Isonzo disaster.", "Punir negligências e reestruturar o comando.", "Punish negligence and restructure command.", "Concentrar esforços na frente do Piave.", "Concentrate efforts on the Piave front."),
    20: ("Governo Orlando de Resistência Nacional", "Orlando Resistance Cabinet", "Vittorio Emanuele Orlando proclama a resistência inflexível no Piave.", "Vittorio Emanuele Orlando proclaims unyielding resistance on the Piave.", "Resistir até o último homem!", "Resist to the last man!", "Garantir a coesão das retaguardas.", "Secure rear-area cohesion."),
    21: ("O Clamor da Vitória Mutilada", "Cry of the Mutilated Victory", "Nacionalistas denunciam a recusa dos aliados em cumprir o Pacto de Londres.", "Nationalists decry the Allied refusal to fulfill the London Pact.", "Exigir o cumprimento integral de nossas terras!", "Demand full fulfillment of our lands!", "Adotar moderação diplomática.", "Adopt diplomatic moderation."),
    22: ("O Gabinete Nitti Assume", "Nitti Cabinet Takes Office", "Francesco Saverio Nitti busca restaurar o equilíbrio fiscal e social.", "Francesco Saverio Nitti seeks fiscal balance and social order.", "Estabilizar a economia e desmobilizar.", "Stabilize the economy and demobilise.", "Manter despesas sociais ativas.", "Maintain active social spending."),
    23: ("Fundação do Partito Popolare Italiano", "Foundation of the PPI", "Don Luigi Sturzo funda o partido cristão-democrata italiano.", "Don Luigi Sturzo founds the Italian Christian Democratic Party.", "Acolher o novo partido democrático.", "Welcome the new democratic party.", "Manter vigilância sobre suas alas.", "Maintain scrutiny over its wings."),
    24: ("Ocupação das Fábricas em Turim", "Turin Factory Occupations", "Operários metalúrgicos ocupam fábricas e erguem conselhos de gestão.", "Metalworkers occupy plants and raise management councils.", "Buscar acordo e mediação pacífica.", "Seek peaceful mediation and agreement.", "Reprimir com a força pública.", "Repress with public forces."),
    25: ("A Crise da Marcha sobre Roma", "March on Rome Crisis", "Colunas de camisas-negras avançam sobre a capital exigindo o poder.", "Blackshirt columns march on the capital demanding state power.", "Evitar a guerra civil e nomear novo governo.", "Avert civil war and appoint new leadership.", "Declarar estado de sítio imediatamente.", "Declare state of siege immediately."),
    26: ("Consulta da Tríplice Aliança", "Triple Alliance Consultation", "Encontro diplomático em Roma revisa as cláusulas de defesa mútua.", "Diplomatic meeting in Rome reviews mutual defense clauses.", "Confirmar cooperação defensiva.", "Confirm defensive cooperation.", "Ressaltar nossos interesses marítimos.", "Highlight our maritime interests."),
    27: ("Renovação da Tríplice Aliança", "Renewal of the Triple Alliance", "O tratado com a Alemanha e a Áustria-Hungria é estendido formalmente.", "The treaty with Germany and Austria-Hungary is formally extended.", "Assinar a prorrogação do tratado.", "Sign the treaty extension.", "Exigir garantias adicionais.", "Demand additional guarantees."),
    28: ("Entendimento Naval com a Grã-Bretanha", "Naval Entente with Great Britain", "Conversações secretas garantem a segurança das rotas do Mediterrâneo.", "Secret talks ensure safety of Mediterranean sea lanes.", "Firmar acordo de cavalheiros naval.", "Sign naval gentlemen's agreement.", "Limitar o alcance dos entendimentos.", "Limit the scope of understandings."),
    29: ("Aproximação Franco-Italiana", "Franco-Italian Understanding", "Acordo diplomático reconhece interesses no norte da África.", "Diplomatic accord recognizes spheres in North Africa.", "Selar a reconciliação latina.", "Seal Latin reconciliation.", "Manter postura de cautela.", "Maintain cautious stance."),
    30: ("A Questão Albanesa no Adriático", "Albanian Adriatic Question", "Tensão diplomática sobre a independência e as fronteiras da Albânia.", "Diplomatic tension over Albanian independence and borders.", "Assegurar presença italiana em Vlora.", "Secure Italian presence in Vlora.", "Negociar compromisso com Belgrado.", "Negotiate compromise with Belgrade."),
    31: ("Conferência de Londres sobre os Bálcãs", "London Conference on Balkans", "As grandes potências decidem o estatuto dos estados balcânicos.", "Great powers deliberate on the Balkan settlement.", "Aceitar a mediação britânica.", "Accept British mediation.", "Exigir garantias estratégicas.", "Demand strategic guarantees."),
    32: ("A Crise de Julho e o Artigo VII", "July Crisis and Article VII", "A Itália contesta a ação austríaca sem consulta prévia nos Bálcãs.", "Italy contests Austrian unilateral action in the Balkans.", "Exigir compensações formais imediatas.", "Demand immediate formal compensations.", "Aguardar o desenrolar dos fatos.", "Await the unfolding of events."),
    33: ("Declaração de Neutralidade Italiana", "Italian Declaration of Neutrality", "O governo declara formalmente a neutralidade italiana no conflito.", "The government formally declares Italian neutrality in the conflict.", "Preservar a paz da nação.", "Preserve the nation's peace.", "Iniciar preparativos secretos de guerra.", "Initiate secret preparations for war."),
    34: ("Missão de von Bülow em Roma", "Von Bülow Mission in Rome", "Berlim envia diplomata para mediar concessões territoriais austríacas.", "Berlin dispatches envoy to mediate Austrian territorial concessions.", "Ouvir a proposta com reserva.", "Listen to proposals with reserve.", "Rejeitar concessões parciais.", "Reject partial concessions."),
    35: ("Assinatura do Pacto de Londres", "Signing of the London Pact", "A Itália assina o tratado secreto com os Aliados na Grã-Bretanha.", "Italy signs secret treaty with the Allies in Great Britain.", "Compromisso selado com a Entente!", "Compact sealed with the Entente!", "Adiar ratificação formal.", "Postpone formal ratification."),
    36: ("Denúncia da Tríplice Aliança", "Denunciation of the Triple Alliance", "O governo notifica Viena e Berlim da revogação do tratado.", "The government notifies Vienna and Berlin of alliance repeal.", "Notificar formalmente os aliados centrais.", "Formally notify central allies.", "Propor conferência de última hora.", "Propose eleventh-hour conference."),
    37: ("Declaração de Guerra à Áustria-Hungria", "Declaration of War on Austria", "A Itália inicia operações militares ao longo do rio Isonzo.", "Italy opens military operations along the Isonzo river.", "Às armas! Pela libertação de Trento e Trieste!", "To arms! For the liberation of Trento and Trieste!", "Garantir a defesa das fronteiras.", "Secure frontier defenses."),
    38: ("Declaração de Guerra à Alemanha", "Declaration of War on Germany", "A Itália estende formalmente o estado de guerra ao Império Alemão.", "Italy formally extends the state of war to the German Empire.", "Solidariedade plena com as Potências Ocidentais.", "Full solidarity with the Western Powers.", "Limitar ação militar direta.", "Limit direct military engagement."),
    39: ("O Contingente Italiano em Salônica", "Italian Contingent in Salonika", "A 35ª Divisão desembarca na Grécia para apoiar a frente balcânica.", "The 35th Division lands in Greece to reinforce the Balkan front.", "Desdobrar as tropas no front macedônio.", "Deploy troops to the Macedonian front.", "Manter papel de reserva.", "Maintain reserve role."),
    40: ("Acordo de Saint-Jean-de-Maurienne", "Saint-Jean-de-Maurienne Accord", "Aliados delimitam esferas futuras na Anatólia e no Levante.", "Allies delimit future spheres in Anatolia and the Levant.", "Assegurar direitos sobre Esmirna.", "Secure rights over Smyrna.", "Focar exclusivamente no Adriático.", "Focus exclusively on the Adriatic."),
    41: ("A Nota de Paz do Papa Bento XV", "Pope Benedict XV's Peace Note", "O Vaticano conclama todas as potências beligerantes a encerrar a luta.", "The Vatican calls upon warring nations to end hostilities.", "Responder com diplomacia respeitosa.", "Reply with respectful diplomacy.", "Reafirmar nossos objetivos sagrados de guerra.", "Reaffirm sacred war objectives."),
    42: ("Congresso dos Povos Oprimidos em Roma", "Congress of Oppressed Peoples", "Líderes de minorias do Império Austro-Húngaro reúnem-se na Itália.", "Leaders of Habsburg minority nationalities gather in Italy.", "Apoiar a autodeterminação dos povos.", "Support self-determination of nationalities.", "Preservar reivindicações italianas no Adriático.", "Preserve Italian Adriatic claims."),
    43: ("O Presidente Wilson e o Adriático", "President Wilson and the Adriatic", "A delegação americana contesta os termos do Tratado de Londres.", "The American delegation contests terms of the Treaty of London.", "Defender nossos direitos históricos com vigor.", "Defend our historic rights vigorously.", "Propor linha de fronteira de compromisso.", "Propose compromise frontier line."),
    44: ("Retirada Italiana de Paris", "Italian Walkout from Paris", "Orlando e Sonnino abandonam temporariamente as negociações em Paris.", "Orlando and Sonnino temporarily walk out of Paris peace talks.", "Protestar contra a intransigência dos Aliados!", "Protest against Allied intransigence!", "Retornar à mesa de negociações.", "Return to negotiating table."),
    45: ("Ratificação de Saint-Germain", "Ratification of Saint-Germain", "O tratado formaliza a soberania italiana sobre Trento, Tirol e Ístria.", "The treaty confirms Italian sovereignty over Trento, Tyrol, and Istria.", "Ratificar o tratado de paz.", "Ratify the peace treaty.", "Registrar reservas sobre a Dalmácia.", "Record reservations on Dalmatia."),
    46: ("O Tratado de Rapallo com Belgrado", "Treaty of Rapallo with Belgrade", "Itália e Iugoslávia chegam a acordo sobre fronteiras adriáticas.", "Italy and Yugoslavia reach accord on Adriatic frontiers.", "Assinar o compromisso pacífico.", "Sign the peaceful compromise.", "Recusar concessões territoriais.", "Refuse territorial concessions."),
    47: ("Tratado Naval de Washington", "Washington Naval Treaty", "A conferência internacional estabelece tetos de tonelagem naval.", "International conference fixes naval tonnage limits.", "Aceitar a paridade com a França.", "Accept parity with France.", "Buscar cotas de cruzeiros adicionais.", "Seek additional cruiser quotas."),
    48: ("Incidente de Corfu", "Corfu Incident", "A marinha bombardeia a ilha grega após o assassinato da missão Tellini.", "The navy bombards Greek island after assassination of Tellini mission.", "Exigir reparações e desculpas imediatas.", "Demand immediate reparations and apologies.", "Submeter o caso à Liga das Nações.", "Submit case to League of Nations."),
    49: ("Resposta às Concessões Austríacas", "Response to Austrian Concessions", "Viena apresenta proposta oficial de cessão territorial mediante neutralidade.", "Vienna submits official proposal of territorial cession for neutrality.", "Aceitar a oferta de paz garantida.", "Accept guaranteed peace offer.", "Rejeitar: somente a vitória trará justiça!", "Reject: only victory will bring justice!"),
    50: ("Protocolo de Escolta Britânica", "British Escort Protocol", "O Almirantado britânico oferece escolta coordenada de comboios.", "British Admiralty offers coordinated convoy escorts.", "Integrar nossas patrulhas às frotas aliadas.", "Integrate patrols with allied fleets.", "Manter operações estritamente nacionais.", "Maintain strictly national operations."),
    51: ("Proposta Diplomática sobre a Líbia", "Diplomatic Proposal on Libya", "Roma apresenta proposta de transferência pacífica da soberania sobre a Líbia.", "Rome submits diplomatic terms for peaceful transfer of sovereignty over Libya.", "Aceitar o acordo e as compensações financeiras.", "Accept accord and financial compensations.", "Rejeitar a ingerência estrangeira!", "Reject foreign interference!"),
    52: ("O Tratado de Ouchy Ratificado", "Treaty of Ouchy Ratified", "A Sublime Porta reconhece formalmente a soberania italiana sobre a Líbia.", "The Sublime Porte formally recognizes Italian sovereignty over Libya.", "A Quarta Margem é nossa!", "The Fourth Shore is ours!", "Celebrar a pacificação do Mediterrâneo.", "Celebrate Mediterranean pacification."),
    53: ("Impasse nas Conversações sobre Trípoli", "Deadlock over Tripoli Talks", "A Sublime Porta recusa os termos apresentados pela diplomacia italiana.", "The Sublime Porte refuses diplomatic terms presented by Italy.", "Manter vigilância naval reforçada.", "Maintain heightened naval vigilance.", "Redobrar esforços diplomáticos.", "Redouble diplomatic efforts."),
    54: ("A Conquista de Gorízia", "Capture of Gorizia", "As tropas italianas cruzam o Isonzo e entram na cidade sob aplausos.", "Italian troops cross the Isonzo and liberate the city.", "Viva o Regio Esercito! Gorízia é italiana!", "Long live the Regio Esercito! Gorizia is Italian!", "Fortificar as novas posições defensivas.", "Fortify new defensive positions."),
    55: ("A Ofensiva no Planalto de Bainsizza", "Bainsizza Plateau Offensive", "A 11ª Batalha do Isonzo conquista as posições elevadas de Bainsizza.", "The 11th Battle of the Isonzo captures high plateau positions.", "Manter o ímpeto do ataque!", "Maintain momentum of the attack!", "Consolidar a linha alcançada.", "Consolidate the line reached."),
    56: ("A Crise de Caporetto", "Caporetto Crisis", "O rompimento inimigo em Caporetto força a retirada geral para o Piave.", "Enemy breakthrough at Caporetto forces retreat to the Piave.", "Manter a linha no Piave a todo custo!", "Hold the line on the Piave at all costs!", "Reagrupar divisões e restabelecer a ordem.", "Regroup divisions and restore discipline."),
    57: ("O Milagre no Piave", "Miracle on the Piave", "O exército resiste heroicamente ao longo do rio Piave e no Monte Grappa.", "The army heroically holds the line on the Piave and Mount Grappa.", "Não passarão! O Piave não se rende!", "They shall not pass! The Piave will not yield!", "Reforçar as fortificações fluviais.", "Strengthen river fortifications."),
    58: ("Armando Diaz Assume o Comando", "Armando Diaz Takes Command", "O novo comandante-geral reorganiza as forças e prioriza a moral da tropa.", "The new supreme commander reorganizes forces and prioritizes troop welfare.", "Confiar na nova liderança militar.", "Place faith in the new military leadership.", "Apoiar a reorganização técnica.", "Support technical reorganization."),
    59: ("A Batalha do Solstício", "Battle of the Solstice", "A ofensiva desesperada austro-húngara é rechaçada com pesadas baixas.", "The desperate Austro-Hungarian offensive is repulsed with heavy losses.", "A vitória está ao nosso alcance!", "Victory is within our reach!", "Preparar o contra-ataque decisivo.", "Prepare the decisive counter-stroke."),
    60: ("O Triunfo de Vittorio Veneto", "Triumph of Vittorio Veneto", "A grande ofensiva quebra as defesas inimigas e liberta todas as cidades.", "The grand offensive smashes enemy lines and frees all northern cities.", "Trento e Trieste finalmente redimidas!", "Trento and Trieste finally redeemed!", "Celebrar a glória das armas italianas.", "Celebrate the glory of Italian arms."),
    61: ("O Armistício de Villa Giusti", "Armistice of Villa Giusti", "A Áustria-Hungria assina a rendição incondicional na Villa Giusti.", "Austria-Hungary signs unconditional surrender at Villa Giusti.", "A guerra terminou com a nossa vitória!", "The war has ended in our victory!", "Iniciar a desmobilização pacífica.", "Begin peaceful demobilisation."),
    62: ("A Ocupação de Fiume por D'Annunzio", "D'Annunzio Occupies Fiume", "Legionários voluntários marcham sobre Fiume e proclamam sua união à Itália.", "Volunteer legionaries march on Fiume and proclaim union with Italy.", "Apoiar a ousadia dos legionários.", "Support the legionaries' boldness.", "Exigir respeito aos tratados legais.", "Demand respect for legal treaties."),
    63: ("A Regência Italiana de Carnaro", "Italian Regency of Carnaro", "D'Annunzio promulga a Carta do Carnaro com constituição revolucionária.", "D'Annunzio promulgates the Charter of Carnaro with unique constitution.", "Observar com fascínio a experiência.", "Observe the experiment with fascination.", "Isolar o regime dissidente.", "Isolate the dissident regime."),
    64: ("O Natal de Sangue em Fiume", "Bloody Christmas in Fiume", "A marinha e tropas do governo desocupam Fiume para cumprir Rapallo.", "Navy and regular troops evacuate Fiume in compliance with Rapallo.", "A lei e a ordem internacional prevalecem.", "Law and international order prevail.", "Lamentar as baixas entre compatriotas.", "Mourn the casualties among compatriots."),
    65: ("O Soldado Desconhecido no Vittoriano", "Unknown Soldier at the Vittoriano", "A nação inteira curva-se em Roma perante o túmulo do Milite Ignoto.", "The whole nation bows in Rome before the tomb of the Milite Ignoto.", "Honra eterna aos nossos heróis caídos!", "Eternal honor to our fallen heroes!", "Consolidar a memória sagrada da nação.", "Consolidate the nation's sacred memory."),
    66: ("Inquérito Parlamentar do Mezzogiorno", "Southern Agriculture Inquiry", "Relatórios parlamentares expõem a urgência de crédito e estradas no Sul.", "Parliamentary reports expose urgency of credit and roads in the South.", "Iniciar programas de fomento regional.", "Initiate regional development programs.", "Priorizar obras de saneamento hídrico.", "Prioritize water sanitation projects."),
    67: ("O Boom Automobilístico em Turim", "Turin Automobile Boom", "Novas linhas industriais da FIAT expandem a produção de veículos.", "New FIAT industrial plants expand automotive output.", "Incentivar a expansão mecânica.", "Encourage mechanical expansion.", "Garantir direitos trabalhistas básicos.", "Ensure basic worker rights."),
    68: ("Marco do Aqueduto da Apúlia", "Apulian Aqueduct Milestone", "A água potável chega a novos centros urbanos da região apuliana.", "Drinking water reaches new urban centers across Apulia.", "Um triunfo da engenharia italiana!", "A triumph of Italian engineering!", "Continuar a extensão das canalizações.", "Continue pipeline extensions."),
    69: ("Remessas dos Emigrantes Italianos", "Emigrant Remittances", "O fluxo constante de moeda forte das Américas fortalece as reservas do país.", "Steady flow of hard currency from the Americas bolsters gold reserves.", "Canalizar recursos para poupança produtiva.", "Channel resources into productive savings.", "Apoiar a assistência consular.", "Support consular assistance."),
    70: ("Decreto de Mobilização Industrial", "Industrial Mobilisation Decree", "Comitês regionais subordinam usinas e metalúrgicas às ordens militares.", "Regional committees subordinate metallurgical plants to military orders.", "Tudo pela vitória militar!", "Everything for military victory!", "Assegurar compensação aos proprietários.", "Ensure fair compensation to owners."),
    71: ("A Crise de Suprimento de Carvão", "Coal Supply Crisis", "A escassez de navios mercantes encarece o carvão importado da Grã-Bretanha.", "Shortage of merchant shipping raises prices of imported coal.", "Priorizar transporte ferroviário vital.", "Prioritize vital railway transport.", "Acelerar conversão hidrelétrica.", "Accelerate hydroelectric conversion."),
    72: ("Motins do Pão em Turim", "Turin Bread Riots", "Protestos populares eclodem contra a escassez de cereais e a carestia.", "Popular protests break out against cereal shortages and food costs.", "Garantir farinha e tabelar preços.", "Secure flour and cap consumer prices.", "Dispersar agitações ilegais.", "Disperse illegal agitations."),
    73: ("Afluxo de Refugiados Venezianos", "Venetian Refugee Influx", "Centenas de milhares de civis evacuam a zona de combate do nordeste.", "Hundreds of thousands of civilians evacuate northeastern combat zone.", "Distribuir socorro e alojamento.", "Distribute relief and shelter.", "Mobilizar caridade privada.", "Mobilize private charity."),
    74: ("Comissão dos Lucros de Guerra", "War Profiteering Commission", "Investigação sobre especuladores e enriquecimentos ilícitos no conflito.", "Investigation into speculators and illicit wartime profiteering.", "Confiscar ganhos imorais.", "Confiscate immoral earnings.", "Aplicar penalidades moderadas.", "Apply moderate penalties."),
    75: ("Onda de Greves do Pós-Guerra", "Postwar Strike Wave", "Paralisações em massa reivindicam melhores salários e jornada de oito horas.", "Mass walkouts demand better wages and eight-hour working day.", "Reconhecer jornada de oito horas.", "Recognize eight-hour day.", "Proteger a continuidade dos serviços.", "Protect continuity of essential services."),
    76: ("Falência da Banca Italiana di Sconto", "Banca di Sconto Collapse", "A quebra da grande instituição financeira ameaça o conglomerado Ansaldo.", "Collapse of major financial institution threatens Ansaldo conglomerate.", "Organizar consórcio estatal de resgate.", "Organize state rescue consortium.", "Deixar o mercado absorver a crise.", "Let market absorb the crisis."),
    77: ("Pacto Nacional de Conciliação Fabril", "National Conciliation Pact", "Acordo mediado pelo governo resolve disputas na indústria metalúrgica.", "Government-mediated accord settles disputes in metallurgical industry.", "Celebrar o pacto de produção.", "Celebrate the production pact.", "Manter vigilância sobre as partes.", "Maintain watch over all parties."),
    78: ("Congresso dos Veteranos Arditi", "Arditi Veterans' Congress", "Ex-combatentes das tropas de choque reúnem-se em comício patriótico.", "Shock troop veterans assemble in patriotic convention.", "Reconhecer a bravura dos Arditi.", "Recognize the bravery of the Arditi.", "Integrá-los a forças de segurança.", "Integrate them into security forces.")
}

for eid, (pt_t, en_t, pt_d, en_d, pt_a, en_a, pt_b, en_b) in event_titles.items():
    add(f"ww1_italy.{eid}.t", pt_t, en_t)
    add(f"ww1_italy.{eid}.d", pt_d, en_d)
    add(f"ww1_italy.{eid}.a", pt_a, en_a)
    add(f"ww1_italy.{eid}.b", pt_b, en_b)

# Write to scripts/ita_support_loc.py
out_file = ROOT / "scripts" / "ita_support_loc.py"
content = [
    '"""Generated support localisation dictionaries for Italian WW1 content."""',
    'SUPPORT_LOC_PT = ' + repr(SUPPORT_PT),
    'SUPPORT_LOC_EN = ' + repr(SUPPORT_EN)
]
out_file.write_text("\n\n".join(content) + "\n", encoding="utf-8")
print(f"Generated {out_file} with {len(SUPPORT_PT)} keys.")
