# -*- coding: utf-8 -*-
"""Bilingual localization dictionaries for German Politics & Society wing."""

ENGLISH_LOC = {
    # Trunk Focuses
    'GER_kaiser_wilhelm_personal_rule': "Kaiser Wilhelm II's Personal Rule",
    'GER_kaiser_wilhelm_personal_rule_desc': "Emperor Wilhelm II exercises supreme authority over the German Empire, balancing civilian ministers against the military cabinet and court factions in Berlin.",
    'GER_reichstag_1912_elections': "1912 Reichstag Elections",
    'GER_reichstag_1912_elections_desc': "The landmark elections of 1912 see the Social Democratic Party (SPD) surge to 110 seats, becoming the largest bloc in parliament and precipitating an unprecedented constitutional challenge.",
    'GER_volkerschlacht_centenary_1913': "Centenary of Leipzig",
    'GER_volkerschlacht_centenary_1913_desc': "The dedication of the monumental Völkerschlachtdenkmal commemorates the liberation struggle of 1813, rallying imperial cohesion and national pride across all German lands.",
    'GER_reichstag_social_concessions': "Reichstag Social Concessions",
    'GER_reichstag_social_concessions_desc': "Granting progressive labor reforms and health insurance expansions appeases the growing working-class opposition and forestalls revolutionary unrest in the industrial cities.",
    'GER_appease_the_junkers': "Appease the Prussian Junkers",
    'GER_appease_the_junkers_desc': "Protecting agrarian grain tariffs and aristocratic privileges solidifies the unwavering loyalty of the East Prussian nobility and the conservative officer corps.",
    'GER_prussian_franchise_debate': "Prussian Franchise Debate",
    'GER_prussian_franchise_debate_desc': "The obsolete three-class electoral system in Prussia divides the empire between reactionaries clinging to privilege and reformists demanding universal equal suffrage.",
    'GER_burgfrieden_declaration_1914': "Burgfrieden Declaration",
    'GER_burgfrieden_declaration_1914_desc': "With the outbreak of European war, Kaiser Wilhelm declares: 'I no longer recognize parties, I only recognize Germans!' All domestic disputes are suspended for the Fatherland.",

    # Lane 1 Focuses
    'GER_spartakusbund_proletarian_revolt': "Spartakusbund Proletarian Revolt",
    'GER_spartakusbund_proletarian_revolt_desc': "Karl Liebknecht and Rosa Luxemburg break decisively from bourgeois moderation, rallying workers and soldiers under the red banner of proletarian revolution.",
    'GER_kiel_sailors_revolt': "Kiel Sailors' Mutiny",
    'GER_kiel_sailors_revolt_desc': "Refusing suicidal sortie orders, the stokers and sailors of the High Seas Fleet mutiny in Kiel, raising the red flag over dreadnoughts and forming the first sailors' councils.",
    'GER_proclaim_freie_sozialistische_republik': "Proclaim Freie Sozialistische Republik",
    'GER_proclaim_freie_sozialistische_republik_desc': "From the balcony of the Berlin Palace, Karl Liebknecht proclaims the Free Socialist Republic of Germany, declaring all power to the workers' and soldiers' councils.",
    'GER_berlin_january_mass_strikes': "Berlin Mass General Strikes",
    'GER_berlin_january_mass_strikes_desc': "Hundreds of thousands of armaments workers and revolutionary shop stewards shut down Berlin's factories, demanding peace, bread, and council democracy.",
    'GER_soldiers_and_workers_councils': "Soldiers' and Workers' Councils",
    'GER_soldiers_and_workers_councils_desc': "Establishing sovereign council governance across Bavaria, Saxony, and the Ruhr replaces the old bureaucratic state machinery with direct proletarian democracy.",
    'GER_volksmarinedivision_guard': "Volksmarinedivision Red Guard",
    'GER_volksmarinedivision_guard_desc': "Armed revolutionary sailors form the Volksmarinedivision in Berlin, garrisoning the imperial stables and defending the revolutionary council government.",
    'GER_dissolve_the_junker_officer_caste': "Dissolve the Junker Officer Caste",
    'GER_dissolve_the_junker_officer_caste_desc': "Purging aristocratic Prussian generals and reactionaries from the command hierarchy ensures that military power remains subordinated to elected soldiers' commissars.",
    'GER_socialist_land_and_factory_collectivization': "Socialist Collectivization",
    'GER_socialist_land_and_factory_collectivization_desc': "Expropriating East Prussian Junker estates and nationalizing the Ruhr's coal and steel syndicates transfers economic mastery directly into collective hands.",
    'GER_rote_ruhrarmee_formation': "Formation of the Rote Ruhrarmee",
    'GER_rote_ruhrarmee_formation_desc': "Over fifty thousand armed coal miners and steelworkers form the Red Ruhr Army, creating an invincible vanguard against domestic counter-revolution.",
    'GER_red_high_seas_fleet': "The Red High Seas Fleet",
    'GER_red_high_seas_fleet_desc': "The dreadnoughts and cruisers of the imperial navy are reorganized under elected sailor committees, ready to defend the revolution across the Baltic and North Seas.",
    'GER_alliance_with_soviet_russia': "Treaty of Red Berlin",
    'GER_alliance_with_soviet_russia_desc': "Signing a historic mutual assistance pact with Soviet Russia creates an unshakeable revolutionary axis uniting the industrial power of Germany with Russian resources.",
    'GER_council_economic_planning': "Council Economic Planning",
    'GER_council_economic_planning_desc': "Coordinating production through regional workers' councils eliminates capitalist anarchy in the markets and directs all heavy industry toward social welfare and defense.",
    'GER_soviet_military_advisors': "Red Military Staff Exchange",
    'GER_soviet_military_advisors_desc': "Exchanging tactical instructors and ideological commissars with the Red Army fuses German industrial military science with Soviet revolutionary doctrine.",
    'GER_red_baltic_intervention': "Red Baltic Intervention",
    'GER_red_baltic_intervention_desc': "Deploying revolutionary divisions across the Baltic Sea liberates Latvian and Estonian workers from aristocratic barons and installs fraternal Soviet republics.",
    'GER_liberate_the_polish_proletariat': "Liberate Polish Proletariat",
    'GER_liberate_the_polish_proletariat_desc': "Overthrowing reactionary nationalist cliques in Poland enables the proclamation of the Polish Soviet Republic as an equal partner in the socialist federation.",
    'GER_danubian_soviet_federation': "Danubian Soviet Federation",
    'GER_danubian_soviet_federation_desc': "Supporting Austrian red guards and the Hungarian Soviet Republic under Béla Kun unites the workers of Central Europe into a unified council republic.",
    'GER_liberate_the_balkans_workers': "Liberate the Balkan Proletariat",
    'GER_liberate_the_balkans_workers_desc': "Exporting revolutionary arms and cadres to Romania and Bulgaria overthrows monarchical regimes, establishing socialist council rule across the Balkan peninsula.",
    'GER_export_revolution_to_france': "Export Revolution to France",
    'GER_export_revolution_to_france_desc': "A revolutionary offensive across the Rhine breaks the bourgeois French third republic, resurrecting the historic Paris Commune across all of France.",
    'GER_world_proletarian_revolution': "World Proletarian Revolution",
    'GER_world_proletarian_revolution_desc': "From Berlin to Petrograd, Paris to Vienna, the workers of the world have broken their chains. The world socialist commonwealth is born!",

    # Lane 2 Focuses
    'GER_prussian_franchise_reform': "Prussian Franchise Reform",
    'GER_prussian_franchise_reform_desc': "Abolishing the discriminatory Three-Class Franchise in Prussia establishes universal, equal suffrage and breaks the political monopoly of the agrarian nobility.",
    'GER_prince_max_von_baden_cabinet': "Prince Max von Baden's Cabinet",
    'GER_prince_max_von_baden_cabinet_desc': "Appointing Prince Max of Baden as Chancellor brings the parliamentary majority parties into executive government, subordinating the armed forces to civil authority.",
    'GER_proclaim_deutsche_republik': "Proclaim the German Republic",
    'GER_proclaim_deutsche_republik_desc': "Philipp Scheidemann proclaims the German Democratic Republic from the Reichstag, initiating a peaceful transition to constitutional representative democracy.",
    'GER_repeal_anti_socialist_heritage': "Repeal Repressive Heritage",
    'GER_repeal_anti_socialist_heritage_desc': "Dismantling all surviving Bismarckian restrictions guarantees freedom of assembly, trade union rights, and equal civic dignity for all citizens.",
    'GER_antinationalist_civil_defense': "Reichsbanner Civil Defense",
    'GER_antinationalist_civil_defense_desc': "Forming the Reichsbanner Schwarz-Rot-Gold provides a disciplined civic militia dedicated to defending republican democracy against extremist putschists.",
    'GER_stinnes_legien_social_compromise': "Stinnes-Legien Social Compact",
    'GER_stinnes_legien_social_compromise_desc': "The landmark accord between union leader Carl Legien and industrialist Hugo Stinnes establishes the eight-hour workday, collective bargaining, and joint factory committees.",
    'GER_rathenau_industrial_reorganization': "Rathenau Reorganization Plan",
    'GER_rathenau_industrial_reorganization_desc': "Walther Rathenau's visionary administrative methods organize raw material supply chains, synthetic chemical research, and efficient industrial coordination.",
    'GER_weimar_national_assembly': "Weimar National Assembly",
    'GER_weimar_national_assembly_desc': "Convening in Weimar, the democratically elected constituent assembly enacts one of the most progressive constitutional frameworks in the world.",
    'GER_zentrum_concordat_with_rome': "Zentrum Social Partnership",
    'GER_zentrum_concordat_with_rome_desc': "Strengthening collaboration with the Catholic Center Party guarantees stability in the Rhineland, Bavaria, and Silesia, bridging cultural divisions.",
    'GER_post_war_welfare_and_reconstruction': "Welfare State & Reconstruction",
    'GER_post_war_welfare_and_reconstruction_desc': "Comprehensive national insurance, invalid pensions, and state housing programs restore human dignity and rebuild communities shattered by conflict.",
    'GER_federal_constitutional_balance': "Federal Constitutional Balance",
    'GER_federal_constitutional_balance_desc': "Harmonizing the rights of the southern German states with Prussian administration preserves local autonomy within a cohesive democratic federation.",
    'GER_direct_negotiations_with_woodrow_wilson': "Negotiate on Wilson's 14 Points",
    'GER_direct_negotiations_with_woodrow_wilson_desc': "Approaching President Woodrow Wilson directly establishes peace based on national self-determination, open covenants, and international law.",
    'GER_alsace_lorraine_plebiscite': "Alsace-Lorraine Plebiscite",
    'GER_alsace_lorraine_plebiscite_desc': "Conducting an internationally supervised plebiscite in Alsace-Lorraine resolves the generational territorial dispute with France through democratic consent.",
    'GER_democratic_mitteleuropa_union': "Democratic Mitteleuropa Union",
    'GER_democratic_mitteleuropa_union_desc': "Inviting Austria, Switzerland, Denmark, and the Low Countries into a democratic economic union lowers trade tariffs and builds mutual prosperity.",
    'GER_subjugate_luxembourg_customs': "Incorporate Luxembourg Customs",
    'GER_subjugate_luxembourg_customs_desc': "Securing Luxembourg's permanent integration into the German customs union (Zollverein) with democratic safeguards guarantees mutual economic access.",
    'GER_nordic_democratic_trade_compact': "Nordic Trade Compact",
    'GER_nordic_democratic_trade_compact_desc': "Signing comprehensive trade treaties with Sweden and Norway secures vital Scandinavian iron ore supplies without reliance on military coercion.",
    'GER_guarantee_independent_poland_buffer': "Guarantee Independent Poland",
    'GER_guarantee_independent_poland_buffer_desc': "Recognizing and diplomatically guaranteeing a sovereign democratic Polish state creates a resilient buffer against Eastern authoritarian aggression.",
    'GER_baltic_democratic_confederation': "Baltic Confederation",
    'GER_baltic_democratic_confederation_desc': "Sponsoring democratic self-governance in Lithuania, Latvia, and Estonia integrates the Baltic littoral into our network of defensive alliances.",
    'GER_pan_european_arbitration_league': "Pan-European Arbitration League",
    'GER_pan_european_arbitration_league_desc': "Establishing a permanent European league of democratic nations in Frankfurt guarantees continental peace through collective security and mutual law.",

    # Lane 3 Focuses
    'GER_silent_dictatorship_ohl': "Third OHL Silent Dictatorship",
    'GER_silent_dictatorship_ohl_desc': "Field Marshal von Hindenburg and General Ludendorff assume de facto supreme control over imperial policy, subordinating all state institutions to military necessity.",
    'GER_oust_bethmann_hollweg': "Oust Bethmann-Hollweg",
    'GER_oust_bethmann_hollweg_desc': "Forcing the resignation of Chancellor Bethmann-Hollweg removes the last civilian check on the Supreme Command's total war policies.",
    'GER_hindenburg_program_mobilization': "Hindenburg Program Mobilization",
    'GER_hindenburg_program_mobilization_desc': "The radical Hindenburg Program mandates the immediate doubling of artillery and machine-gun production, converting commercial industry into munitions plants.",
    'GER_patriotic_auxiliary_service_law': "Patriotic Auxiliary Service Law",
    'GER_patriotic_auxiliary_service_law_desc': "Enacting the Gesetz über den vaterländischen Hilfsdienst conscripts the entire civilian male population aged 16 to 60 for mandatory war work.",
    'GER_krupp_ordnance_dictate': "Krupp Mega-Ordnance Dictate",
    'GER_krupp_ordnance_dictate_desc': "Authorizing blank-check state contracts for Friedrich Krupp AG accelerates the production of colossal siege howitzers and long-range super-batteries.",
    'GER_total_war_patriotism_kriegsanleihen': "War Bonds & Total Morale",
    'GER_total_war_patriotism_kriegsanleihen_desc': "Floating massive imperial Kriegsanleihen issues and directing all public media through strict military censorship rallies total national endurance.",
    'GER_sturmtruppen_doctrine_offensive': "Sturmtruppen Infiltration Tactics",
    'GER_sturmtruppen_doctrine_offensive_desc': "Pioneering specialized Stoßtrupp tactics with flamethrowers, submachine guns, and rolling artillery barrages shatters enemy trench lines.",
    'GER_subjugate_the_reichstag_politicians': "Subjugate Reichstag Politicians",
    'GER_subjugate_the_reichstag_politicians_desc': "Suppressing parliamentary peace resolutions and sidelining civilian party leaders maintains the armed forces' absolute grip over imperial direction.",
    'GER_septemberprogramm_war_aims': "Septemberprogramm War Aims",
    'GER_septemberprogramm_war_aims_desc': "Formalizing the 1914 Septemberprogramm as irrevocable war policy establishes German economic and territorial mastery across continental Europe.",
    'GER_unrestricted_submarine_mobilization': "Unrestricted Submarine Warfare",
    'GER_unrestricted_submarine_mobilization_desc': "Ordering U-boats to sink all merchantmen in British waters without warning aims to strangle Great Britain into surrender before American intervention matures.",
    'GER_annexation_of_belgium_and_briey': "Subjugate Belgium & Briey Basin",
    'GER_annexation_of_belgium_and_briey_desc': "Annexing the rich iron ore fields of Briey-Longwy from France and converting Belgium into a permanent military protectorate cements western dominance.",
    'GER_subjugate_romanian_ploesti_oil': "Subjugate Romanian Ploiești Oil",
    'GER_subjugate_romanian_ploesti_oil_desc': "Securing complete monopoly concessions over the Romanian petroleum basins supplies the imperial military machine with inexhaustible fuel.",
    'GER_brest_litovsk_carve_up': "Carve Up the Russian Empire",
    'GER_brest_litovsk_carve_up_desc': "Enforcing the harsh terms of Brest-Litovsk strips the former Russian Empire of its western borderlands, creating a constellation of German satellite states.",
    'GER_establish_generalgouvernement_warschau': "Generalgouvernement Warschau",
    'GER_establish_generalgouvernement_warschau_desc': "Instituting a German military governorship in Warsaw and raising the Polnische Wehrmacht secures our eastern frontier under direct imperial supervision.",
    'GER_finnish_intervention_von_der_goltz': "Finnish Monarchy Intervention",
    'GER_finnish_intervention_von_der_goltz_desc': "Dispatching General von der Goltz's Baltic Sea Division to Finland crushes socialist revolt and installs a German prince on the Finnish throne.",
    'GER_carve_ukrainian_breadbasket': "Carve Ukrainian Breadbasket",
    'GER_carve_ukrainian_breadbasket_desc': "Installing Hetman Pavlo Skoropadsky in Kiev secures vast agricultural requisitions and Donets coal mines to feed our war industries.",
    'GER_operation_faustschlag_crusade': "Operation Faustschlag Offensive",
    'GER_operation_faustschlag_crusade_desc': "Unleashing the massive railway offensive of 1918 drives deep into Russia, seizing Petrograd and enforcing unconditional capitulation.",
    'GER_subjugate_the_danubian_ally': "Subordinate the Danubian Ally",
    'GER_subjugate_the_danubian_ally_desc': "Subordinating the Austro-Hungarian High Command (AOK) directly to German OHL operational direction ends dualist indecision on all fronts.",
    'GER_hegemon_of_continental_europe': "Hegemon of Continental Europe",
    'GER_hegemon_of_continental_europe_desc': "The German Supreme Command stands triumphant over the European continent. Client kingdoms and satellite republics bow to the iron will of Berlin.",

    # Lane 4 Focuses
    'GER_found_vaterlandspartei': "Found Deutsche Vaterlandspartei",
    'GER_found_vaterlandspartei_desc': "Admiral von Tirpitz and Wolfgang Kapp launch the Deutsche Vaterlandspartei, rallying over a million nationalists demanding total victory and vast annexations.",
    'GER_kapp_and_tirpitz_rally': "Kapp & Tirpitz Mass Mobilization",
    'GER_kapp_and_tirpitz_rally_desc': "Mass rallies of veterans, conservative leagues, and industrial magnates reject all compromise peace proposals, demanding unyielding imperial expansion.",
    'GER_militarize_the_entire_society': "Total Militarization of Society",
    'GER_militarize_the_entire_society_desc': "Integrating schools, youth associations, and civil institutions into paramilitary preparation creates a disciplined Spartan nation in arms.",
    'GER_dissolve_the_reichstag': "Dissolve the Reichstag by Decree",
    'GER_dissolve_the_reichstag_desc': "Suspending parliamentary sessions indefinitely and declaring national martial law concentrates all authority in the hands of the nationalist executive.",
    'GER_smash_general_strikes': "Crush Strikes & Dissidents",
    'GER_smash_general_strikes_desc': "Deploying military units and patriotic militias to violently suppress strike movements protects war production against internal sabotage.",
    'GER_alldeutscher_verband_hegemony': "Pan-German League Hegemony",
    'GER_alldeutscher_verband_hegemony_desc': "Heinrich Class and the Pan-German League guide state ideology, steering foreign policy toward unapologetic expansion and ethnic dominance.",
    'GER_siegfrieden_manifesto': "The Siegfrieden Manifesto",
    'GER_siegfrieden_manifesto_desc': "Proclaiming 'Siegfrieden'—Victorious Peace—proves to the world that Germany will accept nothing less than total, unconditional triumphs and annexations.",
    'GER_autarkic_industrial_trusts': "Autarkic Industrial Trusts",
    'GER_autarkic_industrial_trusts_desc': "Forced cartelization of heavy steel, mining, and chemical trusts under state direction ensures total economic self-sufficiency.",
    'GER_crush_marxism_and_defeatism': "Crush Marxism & Defeatism",
    'GER_crush_marxism_and_defeatism_desc': "Imprisoning socialist agitators, shuttering pacifist journals, and executing deserters eradicates defeatist sentiment from the home front.",
    'GER_annex_the_flemish_coast': "Annex the Flemish Coast",
    'GER_annex_the_flemish_coast_desc': "Direct annexation of Zeebrugge, Ostend, and Antwerp turns the Flanders coastline into permanent German naval fortresses aimed at the English Channel.",
    'GER_colonize_the_eastern_frontier_strip': "Colonize Polish Border Strip",
    'GER_colonize_the_eastern_frontier_strip_desc': "Annexing the Polish Border Strip (Polnischer Grenzstreifen) and clearing the land for German agricultural settlers secures our eastern perimeter.",
    'GER_baltic_crusade_landeswehr': "Baltic Crusade Landeswehr",
    'GER_baltic_crusade_landeswehr_desc': "Authorizing the Baltische Landeswehr and German Freikorps to conquer the Baltic provinces establishes the United Baltic Duchy under German nobility.",
    'GER_crush_netherlands_neutrality': "Neutrality Ultimatum to Holland",
    'GER_crush_netherlands_neutrality_desc': "Demanding Dutch compliance with German customs integration and access to the Scheldt estuary secures our western flank or invites blitzkrieg invasion.",
    'GER_pan_german_settlement_east': "Pan-German Eastern Settlement",
    'GER_pan_german_settlement_east_desc': "Sponsoring large-scale migration of ethnic German families into the conquered eastern provinces solidifies permanent cultural hegemony.",
    'GER_subjugate_scandinavia': "Subjugate Scandinavia",
    'GER_subjugate_scandinavia_desc': "Coercing Denmark and Norway into our naval orbit guarantees total control over the Skagerrak and the North Sea approaches.",
    'GER_annex_french_iron_and_channel_ports': "Annex French Channel Ports",
    'GER_annex_french_iron_and_channel_ports_desc': "Demanding Belfort, Longwy, and the Channel port of Dunkirk from defeated France cripples French military revanchism forever.",
    'GER_conquer_transcaucasia_oil': "Conquer Transcaucasian Oil",
    'GER_conquer_transcaucasia_oil_desc': "Dispatching expeditionary corps into Georgia and Azerbaijan seizes the rich Baku oilfields directly, guaranteeing total energy autarky.",
    'GER_mittelafrika_total_empire': "Realize Total Mittelafrika",
    'GER_mittelafrika_total_empire_desc': "Absorbing the Belgian Congo, French Equatorial Africa, and British territories links German East and Southwest Africa into a vast contiguous empire.",
    'GER_unconditional_victory_or_ruin': "Sieg oder Untergang",
    'GER_unconditional_victory_or_ruin_desc': "Total victory or ruin! The German nation has triumphed over all adversaries, erecting a world empire that shall endure through the ages.",

    # Events Localization
    'ww1_germany_events.201.t': "1912 Reichstag Elections",
    'ww1_germany_events.201.d': "The national elections for the Reichstag have concluded with a political earthquake. The Social Democratic Party (SPD) has surged to become the largest single faction in the chamber with 110 deputies. Kaiser Wilhelm II and his conservative ministers face an unyielding progressive majority demanding reform.",
    'ww1_germany_events.201.a': "Seek an accommodation with the parliamentary majority.",
    'ww1_germany_events.201.b': "Rally conservative and clerical deputies to stonewall reform.",

    'ww1_germany_events.202.t': "Crisis of the Prussian Franchise",
    'ww1_germany_events.202.d': "The three-class franchise system in Prussia, which awards massive electoral weight to the wealthiest taxpayers, is facing furious protests across the empire. Progressive parties and socialist unions demand immediate equal suffrage, while the East Prussian Junker aristocracy threatens defiance.",
    'ww1_germany_events.202.a': "Promise gradual reform after the current tensions pass.",
    'ww1_germany_events.202.b': "The Prussian constitution is sacred and unalterable!",

    'ww1_germany_events.210.t': "The Spartakusbund Rises",
    'ww1_germany_events.210.d': "Karl Liebknecht, Rosa Luxemburg, and the radical anti-war socialists of the Spartakusbund have called for an immediate revolutionary general strike. The imperial authorities are losing control of the working-class suburbs of Berlin, Leipzig, and Bremen.",
    'ww1_germany_events.210.a': "Down with imperialist war! All power to the councils!",

    'ww1_germany_events.211.t': "Mutiny in the High Seas Fleet",
    'ww1_germany_events.211.d': "Sailors and stokers at the naval bases in Kiel and Wilhelmshaven have extinguished the boilers and hoisted red banners atop the dreadnoughts. Officers attempting to enforce discipline have been arrested by elected sailor councils.",
    'ww1_germany_events.211.a': "The red fleet belongs to the revolution!",

    'ww1_germany_events.212.t': "Proclamation of the Free Socialist Republic",
    'ww1_germany_events.212.d': "Speaking from the imperial balcony of the Berlin Stadtschloss, Karl Liebknecht has proclaimed the Free Socialist Republic of Germany. Workers' and soldiers' councils have taken over municipal administration across all major cities.",
    'ww1_germany_events.212.a': "Long live the German Council Republic!",

    'ww1_germany_events.213.t': "The Treaty of Red Berlin",
    'ww1_germany_events.213.d': "Envoys from Soviet Russia have arrived in Berlin to conclude a comprehensive military and economic mutual assistance treaty. The industrial might of revolutionary Germany is united with the vast resources of the Russian Soviet Republic.",
    'ww1_germany_events.213.a': "Ratify the socialist alliance!",

    'ww1_germany_events.214.t': "The Danubian Socialist Federation",
    'ww1_germany_events.214.d': "Inspired by our revolution, the Austrian Red Guard and the Hungarian Soviet Republic under Béla Kun have established council governments in Vienna and Budapest, appealing for integration into a Danubian Socialist Federation.",
    'ww1_germany_events.214.a': "Welcome our Danubian brothers into the fold!",

    'ww1_germany_events.220.t': "Proclamation of the German Republic",
    'ww1_germany_events.220.d': "From a window of the Reichstag building in Berlin, Philipp Scheidemann has proclaimed the German Democratic Republic to cheering crowds. Emperor Wilhelm II has vacated his duties, and a provisional government under Friedrich Ebert has assumed power.",
    'ww1_germany_events.220.a': "Long live the German Republic!",

    'ww1_germany_events.221.t': "Negotiations on Wilson's Fourteen Points",
    'ww1_germany_events.221.d': "Our diplomatic envoy has formally contacted President Woodrow Wilson, declaring Germany's readiness to negotiate peace on the explicit basis of the Fourteen Points, including self-determination and the removal of economic barriers.",
    'ww1_germany_events.221.a': "Accept the Fourteen Points as the foundation for peace.",
    'ww1_germany_events.221.b': "Insist on colonial guarantees before agreeing.",

    'ww1_germany_events.222.t': "The Plebiscite in Alsace-Lorraine",
    'ww1_germany_events.222.d': "In accordance with democratic principles, a supervised referendum has been organized in the Reichsland of Alsace-Lorraine. The population has voiced its preference for autonomous status within a peaceful Europe, defusing centuries of revanchism.",
    'ww1_germany_events.222.a': "Respect the popular will of the borderlands.",

    'ww1_germany_events.230.t': "The Third OHL Assumes Control",
    'ww1_germany_events.230.d': "Field Marshal Paul von Hindenburg and General Erich Ludendorff have assumed absolute control over the Supreme War Command (Oberste Heeresleitung). The Kaiser has agreed to endorse all military directives, subordinating civilian ministers to the front.",
    'ww1_germany_events.230.a': "Victory requires iron discipline!",

    'ww1_germany_events.231.t': "Declaration of Unrestricted Submarine Warfare",
    'ww1_germany_events.231.d': "The Supreme Command has ordered the resumption of unrestricted submarine warfare in all waters surrounding the British Isles. All vessels, belligerent or neutral, will be targeted without prior warning in an effort to starve Britain into submission.",
    'ww1_germany_events.231.a': "Let the U-boats unleash total blockade!",
    'ww1_germany_events.231.b': "Heed the diplomatic dangers and maintain prize rules.",

    'ww1_germany_events.232.t': "The Dismemberment of the Russian Empire",
    'ww1_germany_events.232.d': "Following our eastern victories and the treaties of Brest-Litovsk, the former Russian Empire has ceded vast territories in Poland, Ukraine, Belarus, and the Baltic. A network of German client states is being erected to shield our eastern marches.",
    'ww1_germany_events.232.a': "The East is ours!",

    'ww1_germany_events.240.t': "Founding of the Deutsche Vaterlandspartei",
    'ww1_germany_events.240.d': "Grand Admiral Alfred von Tirpitz and Wolfgang Kapp have established the Deutsche Vaterlandspartei in Königsberg. Over one million citizens have enrolled within weeks, demanding total annexationist peace (Siegfrieden) and rejecting any compromise.",
    'ww1_germany_events.240.a': "For Kaiser, Volk, and Imperial Glory!",

    'ww1_germany_events.241.t': "The Dissolution of the Reichstag",
    'ww1_germany_events.241.d': "Faced with persistent criticism from liberal and socialist deputies, the government has dissolved the Reichstag by imperial decree. The nation is placed under full martial law, silencing defeatist voices for the duration of the war.",
    'ww1_germany_events.241.a': "National survival supersedes parliamentary debate!",

    'ww1_germany_events.242.t': "Ultimatum to the Low Countries",
    'ww1_germany_events.242.d': "Our government has dispatched an uncompromising ultimatum to the government of the Netherlands, demanding immediate incorporation into the German customs network and access to naval installations along the Rhine delta.",
    'ww1_germany_events.242.a': "They must bend to our will or face our arms!",

    # Ideas Localization
    'GER_wilhelmine_personal_regime': "Wilhelmine Personal Regime",
    'GER_wilhelmine_reform_regime': "Reformed Wilhelmine Constitutionalism",
    'GER_volkerschlacht_spirit': "Spirit of the Battle of the Nations",
    'GER_burgfrieden_1914': "Burgfrieden Civil Truce",
    'GER_rate_republik': "Socialist Council Republic",
    'GER_red_commissars': "Soldiers' Councils & Commissars",
    'GER_ruhr_proletariat': "Rote Ruhrarmee Mobilization",
    'GER_world_revolution_vanguard': "Vanguard of World Revolution",
    'GER_weimar_democracy': "Weimar Democratic Constitutionalism",
    'GER_zollverein_subordination': "German Zollverein Subordination",
    'GER_hindenburg_program': "The Hindenburg Program",
    'GER_operation_faustschlag_timed': "Operation Faustschlag Spearhead",
    'GER_continental_hegemony': "Continental European Hegemony",
    'GER_ohl_supreme_staff_coordination': "OHL Operational Staff Coordination",
    'GER_vaterlandspartei_movement': "Vaterlandspartei Mass Movement",
    'GER_siegfrieden_triumph': "Siegfrieden Imperial Triumph",

    # Decisions Localization
    'GER_council_republic_revolution': "Proletarian Council Revolution",
    'ger_council_nationalize_heavy_syndicates': "Nationalize Heavy Syndicates",
    'ger_council_red_guard_militia_call': "Mobilize Red Guard Volunteers",
    'ger_council_propaganda_austria': "Agitate for Danubian Council Rule",
    'GER_weimar_democratic_diplomacy': "Weimar Democratic Diplomacy",
    'ger_weimar_frankfurt_peace_congress': "Convene Frankfurt Peace Congress",
    'ger_weimar_expand_customs_treaty': "Expand Central European Customs Treaty",
    'ger_weimar_rhineland_pacification': "Pacify Industrial Rhineland",
    'GER_ohl_total_mobilization': "OHL Total Mobilization Decrees",
    'ger_ohl_requisition_civilian_workshops': "Requisition Civilian Workshops",
    'ger_ohl_enforce_labor_quotas': "Enforce Auxiliary Labor Quotas",
    'ger_ohl_deploy_sturmtruppen_spearhead': "Deploy Sturmtruppen Spearhead",
    'GER_pan_german_annexations': "Pan-German Annexations & Colonization",
    'ger_pan_german_resettle_border_strip': "Settle Polish Border Strip",
    'ger_pan_german_annex_antwerp_harbor': "Fortify Antwerp Harbor Bastion",
    'ger_pan_german_caucasus_oil_concession': "Extract Baku Petroleum Reserves",
}

BRAZ_POR_LOC = {
    # Trunk Focuses
    'GER_kaiser_wilhelm_personal_rule': "Governo Pessoal do Kaiser Wilhelm II",
    'GER_kaiser_wilhelm_personal_rule_desc': "O Imperador Wilhelm II exerce autoridade suprema sobre o Império Alemão, equilibrando ministros civis contra o gabinete militar e as facções da corte em Berlim.",
    'GER_reichstag_1912_elections': "Eleições do Reichstag de 1912",
    'GER_reichstag_1912_elections_desc': "As históricas eleições de 1912 consagram a ascensão do Partido Social-Democrata (SPD), que alcança 110 assentos e se torna o maior bloco parlamentar, abrindo uma crise constitucional sem precedentes.",
    'GER_volkerschlacht_centenary_1913': "Centenário da Batalha de Leipzig",
    'GER_volkerschlacht_centenary_1913_desc': "A inauguração solene do Völkerschlachtdenkmal comemora a libertação de 1813, reacendendo o orgulho nacional e a coesão imperial por todas as terras alemãs.",
    'GER_reichstag_social_concessions': "Concessões Sociais do Reichstag",
    'GER_reichstag_social_concessions_desc': "A aprovação de reformas trabalhistas progressistas e a expansão do seguro-saúde acalmam a oposição operária e contêm revoltas nas cidades industriais.",
    'GER_appease_the_junkers': "Apaziguar os Junkers Prussianos",
    'GER_appease_the_junkers_desc': "A proteção às tarifas agrícolas de grãos e aos privilégios aristocráticos assegura a lealdade incondicional da nobreza da Prússia Oriental e do corpo de oficiais conservadores.",
    'GER_prussian_franchise_debate': "Debate do Voto Tripartido Prussiano",
    'GER_prussian_franchise_debate_desc': "O obsoleto sistema eleitoral de três classes na Prússia divide o império entre reacionários apegados a privilégios e reformistas exigindo sufrágio universal e igualitário.",
    'GER_burgfrieden_declaration_1914': "Declaração de Burgfrieden",
    'GER_burgfrieden_declaration_1914_desc': "Com a eclosão da guerra europeia, o Kaiser declara: 'Não reconheço mais partidos, apenas reconheço alemães!' Todas as disputas políticas são suspensas pela Pátria.",

    # Lane 1 Focuses
    'GER_spartakusbund_proletarian_revolt': "Revolta Proletária do Spartakusbund",
    'GER_spartakusbund_proletarian_revolt_desc': "Karl Liebknecht e Rosa Luxemburg rompem decisivamente com o reformismo burguês, unindo operários e soldados sob a bandeira vermelha da revolução proletária.",
    'GER_kiel_sailors_revolt': "Motim dos Marinheiros de Kiel",
    'GER_kiel_sailors_revolt_desc': "Recusando ordens de batalha suicidas, os foguistas e marinheiros da Frota de Alto-Mar amotinam-se em Kiel, hasteando a bandeira vermelha nos encouraçados e criando conselhos de marinheiros.",
    'GER_proclaim_freie_sozialistische_republik': "Proclamar a República Socialista Livre",
    'GER_proclaim_freie_sozialistische_republik_desc': "Da sacada do Palácio de Berlim, Karl Liebknecht proclama a República Socialista Livre da Alemanha, decretando todo o poder aos conselhos de operários e soldados.",
    'GER_berlin_january_mass_strikes': "Greve Geral de Massas em Berlim",
    'GER_berlin_january_mass_strikes_desc': "Centenas de milhares de operários armamentistas e delegados sindicais revolucionários paralisam as fábricas de Berlim, exigindo paz, pão e democracia dos conselhos.",
    'GER_soldiers_and_workers_councils': "Conselhos de Soldados e Operários",
    'GER_soldiers_and_workers_councils_desc': "A consolidação do poder dos conselhos (Räterepublik) na Baviera, Saxônia e Ruhr substitui o antigo aparato burocrático pela democracia operária direta.",
    'GER_volksmarinedivision_guard': "Divisão Naval Popular",
    'GER_volksmarinedivision_guard_desc': "Marinheiros revolucionários armados formam a Volksmarinedivision em Berlim, ocupando as cavalariças imperiais e defendendo o governo revolucionário dos conselhos.",
    'GER_dissolve_the_junker_officer_caste': "Dissolver a Casta de Oficiais Junkers",
    'GER_dissolve_the_junker_officer_caste_desc': "A expurgação dos generais prussianos aristocráticos assegura que o comando militar permaneça subordinado aos comissários eleitos pelos próprios soldados.",
    'GER_socialist_land_and_factory_collectivization': "Coletivização Socialista",
    'GER_socialist_land_and_factory_collectivization_desc': "A desapropriação dos latifúndios aristocráticos da Prússia Oriental e a nacionalização dos monopólios do carvão e aço do Ruhr transferem o poder econômico à classe trabalhadora.",
    'GER_rote_ruhrarmee_formation': "Formação do Exército Vermelho do Ruhr",
    'GER_rote_ruhrarmee_formation_desc': "Mais de cinquenta mil mineiros e operários fabris armados formam o Rote Ruhrarmee, criando uma vanguarda impenetrável contra a contrarrevolução.",
    'GER_red_high_seas_fleet': "A Frota Vermelha de Alto-Mar",
    'GER_red_high_seas_fleet_desc': "Os encouraçados e cruzadores da marinha imperial são reorganizados sob comitês de marinheiros, prontos para defender a revolução no Báltico e no Mar do Norte.",
    'GER_alliance_with_soviet_russia': "Tratado de Berlim Vermelha",
    'GER_alliance_with_soviet_russia_desc': "A assinatura de um pacto histórico de auxílio mútuo com a Rússia Soviética forja um eixo revolucionário unindo o parque industrial alemão aos imensos recursos russos.",
    'GER_council_economic_planning': "Planejamento Econômico dos Conselhos",
    'GER_council_economic_planning_desc': "A coordenação da produção através dos sindicatos e conselhos elimina a anarquia de mercado capitalista e orienta a indústria pesada para o bem-estar e a defesa social.",
    'GER_soviet_military_advisors': "Intercâmbio Militar Soviético",
    'GER_soviet_military_advisors_desc': "O intercâmbio de oficiais táticos e comissários com o Exército Vermelho combina a ciência militar industrial alemã à doutrina revolucionária soviética.",
    'GER_red_baltic_intervention': "Intervenção Vermelha no Báltico",
    'GER_red_baltic_intervention_desc': "O envio de divisões revolucionárias pelo Báltico liberta os trabalhadores letões e estonianos dos barões aristocráticos e instala comunas soviéticas fraternas.",
    'GER_liberate_the_polish_proletariat': "Libertação do Proletariado Polonês",
    'GER_liberate_the_polish_proletariat_desc': "Derrubar as elites nacionalistas reacionárias na Polônia permite a proclamação da República Soviética Polonesa como parceira igualitária na federação socialista.",
    'GER_danubian_soviet_federation': "Federação Socialista Danubiana",
    'GER_danubian_soviet_federation_desc': "Apoiar a Guarda Vermelha austríaca e a República Soviética Húngara de Béla Kun une os trabalhadores da Europa Central em uma federação unificada de conselhos.",
    'GER_liberate_the_balkans_workers': "Libertação Proletária dos Bálcãs",
    'GER_liberate_the_balkans_workers_desc': "Exportar armamentos e comissários para a Romênia e Bulgária derruba as dinastias locais e instaura o poder operário na península balcânica.",
    'GER_export_revolution_to_france': "Exportar a Revolução para a França",
    'GER_export_revolution_to_france_desc': "Uma ofensiva revolucionária pelo Reno quebra a Terceira República burguesa, ressuscitando a lendária Comuna de Paris em toda a França.",
    'GER_world_proletarian_revolution': "Revolução Proletária Mundial",
    'GER_world_proletarian_revolution_desc': "De Berlim a Petrogrado, de Paris a Viena, os trabalhadores do mundo romperam seus grilhões. Nasce a união socialista global!",

    # Lane 2 Focuses
    'GER_prussian_franchise_reform': "Reforma Eleitoral Prussiana",
    'GER_prussian_franchise_reform_desc': "A abolição do discriminatório voto de três classes na Prússia institui o sufrágio universal e igualitário, rompendo o monopólio da nobreza agrária.",
    'GER_prince_max_von_baden_cabinet': "Gabinete do Príncipe Max de Baden",
    'GER_prince_max_von_baden_cabinet_desc': "A nomeação do Príncipe Max de Baden traz a maioria partidária parlamentar para o governo executivo, subordinando os militares ao poder civil.",
    'GER_proclaim_deutsche_republik': "Proclamar a República Alemã",
    'GER_proclaim_deutsche_republik_desc': "Philipp Scheidemann proclama a República Democrática Alemã do balcão do Reichstag, iniciando uma transição pacífica para a democracia representativa.",
    'GER_repeal_anti_socialist_heritage': "Revogação das Leis Repressivas",
    'GER_repeal_anti_socialist_heritage_desc': "O desmantelamento das leis bismarckianas garante plena liberdade de reunião, direitos sindicais e igualdade jurídica a todos os cidadãos.",
    'GER_antinationalist_civil_defense': "Defesa Civil Reichsbanner",
    'GER_antinationalist_civil_defense_desc': "A formação da milícia Reichsbanner Schwarz-Rot-Gold cria uma guarda cívica dedicada a defender a república contra tentativas de golpe extremistas.",
    'GER_stinnes_legien_social_compromise': "Pacto Social Stinnes-Legien",
    'GER_stinnes_legien_social_compromise_desc': "O acordo histórico entre o líder sindical Carl Legien e o industrial Hugo Stinnes estabelece a jornada de 8 horas, negociação coletiva e comissões de fábrica.",
    'GER_rathenau_industrial_reorganization': "Reorganização Industrial de Rathenau",
    'GER_rathenau_industrial_reorganization_desc': "O plano administrativo de Walther Rathenau aperfeiçoa as cadeias de suprimentos, incentiva a química sintética e otimiza a produção de matérias-primas.",
    'GER_weimar_national_assembly': "Assembleia Nacional de Weimar",
    'GER_weimar_national_assembly_desc': "Reunida na cidade de Weimar, a assembleia constituinte eleita democraticamente promulga uma das cartas fundamentais mais progressistas do mundo.",
    'GER_zentrum_concordat_with_rome': "Parceria Social do Zentrum",
    'GER_zentrum_concordat_with_rome_desc': "O fortalecimento dos laços com o Partido de Centro Católico garante a conciliação na Renânia, Baviera e Silésia, superando antigas divisões religiosas.",
    'GER_post_war_welfare_and_reconstruction': "Estado de Bem-Estar e Reconstrução",
    'GER_post_war_welfare_and_reconstruction_desc': "Seguro-desemprego universal, pensões para veteranos e planos habitacionais restauram a dignidade pública e reconstroem as cidades atingidas pela guerra.",
    'GER_federal_constitutional_balance': "Equilíbrio Constitucional Federal",
    'GER_federal_constitutional_balance_desc': "Harmonizar os direitos dos estados do sul com a administração prussiana preserva a rica autonomia local em uma federação democrática coesa.",
    'GER_direct_negotiations_with_woodrow_wilson': "Negociar sob os 14 Pontos de Wilson",
    'GER_direct_negotiations_with_woodrow_wilson_desc': "Aproximar-se diretamente do presidente Woodrow Wilson estabelece a paz com base na autodeterminação dos povos e no direito internacional.",
    'GER_alsace_lorraine_plebiscite': "Plebiscito na Alsácia-Lorena",
    'GER_alsace_lorraine_plebiscite_desc': "A realização de um plebiscito supervisionado internacionalmente na Alsácia-Lorena resolve séculos de tensões fronteiriças com a França por meio da vontade popular.",
    'GER_democratic_mitteleuropa_union': "União Democrática da Mitteleuropa",
    'GER_democratic_mitteleuropa_union_desc': "Convidar Áustria, Suíça, Dinamarca e Países Baixos para uma união aduaneira democrática reduz barreiras comerciais e fomenta prosperidade compartilhada.",
    'GER_subjugate_luxembourg_customs': "Integrar Alfândegas de Luxemburgo",
    'GER_subjugate_luxembourg_customs_desc': "Garantir a adesão definitiva de Luxemburgo ao Zollverein com salvaguardas democráticas consolida o livre comércio no coração industrial europeu.",
    'GER_nordic_democratic_trade_compact': "Pacto Comercial Nórdico",
    'GER_nordic_democratic_trade_compact_desc': "Assinar acordos comerciais abrangentes com a Suécia e Noruega assegura suprimentos contínuos de minério de ferro sem recorrer à coerção militar.",
    'GER_guarantee_independent_poland_buffer': "Garantir a Polônia Independente",
    'GER_guarantee_independent_poland_buffer_desc': "O reconhecimento e garantia diplomática a uma república polonesa democrática cria um escudo de proteção estável contra o autoritarismo no leste.",
    'GER_baltic_democratic_confederation': "Confederação Democrática Báltica",
    'GER_baltic_democratic_confederation_desc': "O apoio à autodeterminação na Lituânia, Letônia e Estônia integra o litoral báltico ao nosso sistema de segurança coletiva e comércio pacífico.",
    'GER_pan_european_arbitration_league': "Liga Pan-Europeia de Arbitragem",
    'GER_pan_european_arbitration_league_desc': "Fundar uma liga permanente de nações democráticas sediada em Frankfurt assegura a paz duradoura no continente através do direito e da arbitragem.",

    # Lane 3 Focuses
    'GER_silent_dictatorship_ohl': "Ditadura Silenciosa da Terceira OHL",
    'GER_silent_dictatorship_ohl_desc': "O Marechal Paul von Hindenburg e o General Erich Ludendorff assumem controle supremo dos negócios do Estado, subordinando a administração pública às necessidades da guerra.",
    'GER_oust_bethmann_hollweg': "Demitir Bethmann-Hollweg",
    'GER_oust_bethmann_hollweg_desc': "Forçar a renúncia do chanceler civil Bethmann-Hollweg elimina a última barreira ministerial às diretrizes de guerra total traçadas pelo Alto Comando.",
    'GER_hindenburg_program_mobilization': "Mobilização do Programa Hindenburg",
    'GER_hindenburg_program_mobilization_desc': "O radical Programa Hindenburg impõe a duplicação imediata da produção de artilharia e metralhadoras, convertendo fábricas comerciais em oficinas de guerra.",
    'GER_patriotic_auxiliary_service_law': "Lei de Serviço Auxiliar Patriótico",
    'GER_patriotic_auxiliary_service_law_desc': "A promulgação da lei conscreve compulsoriamente toda a população masculina civil de 16 a 60 anos para o trabalho em complexos industriais armamentistas.",
    'GER_krupp_ordnance_dictate': "Decreto de Super-Artilharia Krupp",
    'GER_krupp_ordnance_dictate_desc': "Contratos estatais irrestritos com a Friedrich Krupp AG aceleram a fabricação de obuses monstruosos e canhões ferroviários de alcance continental.",
    'GER_total_war_patriotism_kriegsanleihen': "Bônus de Guerra e Patriotismo Total",
    'GER_total_war_patriotism_kriegsanleihen_desc': "A emissão maciça de bônus imperiais (Kriegsanleihen) e a censura militar estrita sustentam a resistência nacional diante do bloqueio naval.",
    'GER_sturmtruppen_doctrine_offensive': "Táticas de Infiltração das Sturmtruppen",
    'GER_sturmtruppen_doctrine_offensive_desc': "Batalhões especializados de assalto armados com lança-chamas, submetralhadoras e barragens de artilharia móvel rompem as linhas de trincheiras inimigas.",
    'GER_subjugate_the_reichstag_politicians': "Subjugar os Parlamentares do Reichstag",
    'GER_subjugate_the_reichstag_politicians_desc': "Reprimir as moções de paz parlamentares e silenciar líderes civis garante o domínio absoluto das forças armadas sobre o destino do império.",
    'GER_septemberprogramm_war_aims': "Metas de Guerra do Septemberprogramm",
    'GER_septemberprogramm_war_aims_desc': "Instituir o Septemberprogramm de 1914 como política irrevogável formaliza a dominação econômica e territorial definitiva da Alemanha sobre o continente europeu.",
    'GER_unrestricted_submarine_mobilization': "Guerra Submarina Irrestrita",
    'GER_unrestricted_submarine_mobilization_desc': "Autorizar os submarinos a torpedear qualquer embarcação em águas britânicas visa sufocar o Reino Unido antes que o apoio americano se consolide.",
    'GER_annexation_of_belgium_and_briey': "Subjugar Bélgica e a Bacia de Briey",
    'GER_annexation_of_belgium_and_briey_desc': "A anexação do rico vale de minério de ferro de Briey-Longwy da França e a redução da Bélgica a protetorado militar consolidam nossa hegemonia no oeste.",
    'GER_subjugate_romanian_ploesti_oil': "Subjugar o Petróleo de Ploiești",
    'GER_subjugate_romanian_ploesti_oil_desc': "A apropriação dos campos petrolíferos de Ploiești na Romênia garante combustível farto e inesgotável para os motores da máquina de guerra alemã.",
    'GER_brest_litovsk_carve_up': "Desmantelamento do Império Russo",
    'GER_brest_litovsk_carve_up_desc': "A imposição dos termos de Brest-Litovsk despoja a Rússia de seus territórios ocidentais, erguendo um cordão de estados satélites sob tutela imperial alemã.",
    'GER_establish_generalgouvernement_warschau': "Generalgouvernement Warschau",
    'GER_establish_generalgouvernement_warschau_desc': "A instalação de um governo militar em Varsóvia e a formação da Polnische Wehrmacht garantem a segurança da fronteira leste sob controle imperial.",
    'GER_finnish_intervention_von_der_goltz': "Intervenção Monárquica na Finlândia",
    'GER_finnish_intervention_von_der_goltz_desc': "O envio da Divisão do Mar Báltico do General von der Goltz esmaga os levantes na Finlândia e instala um príncipe alemão no trono finlandês.",
    'GER_carve_ukrainian_breadbasket': "Celeiro Agrícola Ucraniano",
    'GER_carve_ukrainian_breadbasket_desc': "Apoiar o Hetman Pavlo Skoropadsky em Kiev garante o envio contínuo de milhões de toneladas de grãos e carvão de Donets para abastecer nosso front doméstico.",
    'GER_operation_faustschlag_crusade': "Ofensiva da Operação Faustschlag",
    'GER_operation_faustschlag_crusade_desc': "A rápida ofensiva ferroviária de 1918 avança profundamente sobre a Rússia, marchando sobre Petrogrado e impondo rendição incondicional.",
    'GER_subjugate_the_danubian_ally': "Subordinar o Aliado Danubiano",
    'GER_subjugate_the_danubian_ally_desc': "Subordinar o Alto Comando Austro-Húngaro (AOK) diretamente à direção operacional da OHL põe fim à hesitação militar nas frentes conjuntas.",
    'GER_hegemon_of_continental_europe': "Hegemonia Continental Europeia",
    'GER_hegemon_of_continental_europe_desc': "O Alto Comando Alemão reina triunfante sobre a Europa. Reinos clientes e repúblicas satélites curvam-se diante da vontade de ferro de Berlim.",

    # Lane 4 Focuses
    'GER_found_vaterlandspartei': "Fundar a Deutsche Vaterlandspartei",
    'GER_found_vaterlandspartei_desc': "O Grande Almirante von Tirpitz e Wolfgang Kapp fundam a Deutsche Vaterlandspartei, mobilizando mais de um milhão de nacionalistas que exigem vitória total e anexações.",
    'GER_kapp_and_tirpitz_rally': "Mobilização de Massas de Kapp e Tirpitz",
    'GER_kapp_and_tirpitz_rally_desc': "Comícios massivos de veteranos e magnatas industriais rejeitam qualquer compromisso de paz, exigindo a expansão territorial irrestrita do império.",
    'GER_militarize_the_entire_society': "Militarização Total da Sociedade",
    'GER_militarize_the_entire_society_desc': "A integração de escolas, juventudes e associações civis em treinamentos paramilitares transforma o império em uma nação espartana em armas.",
    'GER_dissolve_the_reichstag': "Dissolver o Reichstag por Decreto",
    'GER_dissolve_the_reichstag_desc': "Suspender as sessões parlamentares por tempo indeterminado e declarar lei marcial unifica todos os poderes nas mãos do executivo nacionalista.",
    'GER_smash_general_strikes': "Esmagar Greves e Agitadores",
    'GER_smash_general_strikes_desc': "O destacamento do exército e de milícias patrióticas para sufocar piquetes e prender sabotadores protege a produção bélica contra traições internas.",
    'GER_alldeutscher_verband_hegemony': "Hegemonia da Liga Pan-Germânica",
    'GER_alldeutscher_verband_hegemony_desc': "Heinrich Class e a Liga Pan-Germânica orientam a política externa imperial rumo à expansão intransigente e à supremacia germânica.",
    'GER_siegfrieden_manifesto': "Manifesto da Paz Vitoriosa (Siegfrieden)",
    'GER_siegfrieden_manifesto_desc': "Proclamar o Siegfrieden demonstra ao mundo que a Alemanha não aceitará nada menos do que anexações maciças e a vitória militar absoluta.",
    'GER_autarkic_industrial_trusts': "Trustes Industriais Autárquicos",
    'GER_autarkic_industrial_trusts_desc': "A cartelização forçada dos conglomerados siderúrgicos, químicos e mineradores sob controle estatal garante autossuficiência econômica completa.",
    'GER_crush_marxism_and_defeatism': "Esmagar o Marxismo e o Derrotismo",
    'GER_crush_marxism_and_defeatism_desc': "O encarceramento de agitadores pacifistas e a execução de desertores eliminam qualquer hesitação moral nas cidades e na frente de batalha.",
    'GER_annex_the_flemish_coast': "Anexação da Costa Flamenga",
    'GER_annex_the_flemish_coast_desc': "A incorporação direta de Zeebrugge, Ostend e Antuérpia transforma o litoral de Flandres em bases navais impenetráveis voltadas para o Canal da Mancha.",
    'GER_colonize_the_eastern_frontier_strip': "Colonizar a Faixa de Fronteira Polonesa",
    'GER_colonize_the_eastern_frontier_strip_desc': "Anexar o Polnischer Grenzstreifen e destinar as terras férteis a colonos camponeses alemães cria uma barreira demográfica de segurança permanente no leste.",
    'GER_baltic_crusade_landeswehr': "Cruzada da Baltische Landeswehr",
    'GER_baltic_crusade_landeswehr_desc': "Autorizar a Landeswehr e os Freikorps a dominar as províncias bálticas instaura o Ducado Báltico Unido sob o comando da nobreza alemã.",
    'GER_crush_netherlands_neutrality': "Ultimato de Neutralidade à Holanda",
    'GER_crush_netherlands_neutrality_desc': "Exigir a submissão aduaneira e o controle do delta do Reno aos Países Baixos assegura nosso flanco ocidental ou desencadeia a invasão imediata.",
    'GER_pan_german_settlement_east': "Povoamento Pan-Germânico do Leste",
    'GER_pan_german_settlement_east_desc': "O assentamento em larga escala de famílias alemãs nas províncias conquistadas do leste consolida a hegemonia cultural germânica para as futuras gerações.",
    'GER_subjugate_scandinavia': "Subjugar a Escandinávia",
    'GER_subjugate_scandinavia_desc': "Coagir a Dinamarca e a Noruega garante o controle militar absoluto sobre o estreito de Skagerrak e os portos de apoio aos submarinos no Atlântico.",
    'GER_annex_french_iron_and_channel_ports': "Anexar Portos Franceses do Canal",
    'GER_annex_french_iron_and_channel_ports_desc': "Exigir Belfort, Longwy e o porto estratégico de Dunquerque da França derrotada impede para sempre qualquer revanchismo militar francês.",
    'GER_conquer_transcaucasia_oil': "Conquistar o Petróleo da Transcaucásia",
    'GER_conquer_transcaucasia_oil_desc': "O envio de corpos expedicionários à Geórgia e ao Azerbaijão assegura o controle direto sobre os campos petrolíferos de Baku, garantindo autarquia energética total.",
    'GER_mittelafrika_total_empire': "Concretizar o Império da Mittelafrika",
    'GER_mittelafrika_total_empire_desc': "A incorporação do Congo Belga e das colônias francesas e britânicas conecta a África Oriental à África Ocidental Alemã em um império contínuo colossal.",
    'GER_unconditional_victory_or_ruin': "Vitória ou Ruína Total",
    'GER_unconditional_victory_or_ruin_desc': "Vitória total ou ruína! A nação alemã sobrepujou todos os seus inimigos na terra e nos mares, fundando uma ordem imperial gloriosa e eterna.",

    # Events Localization
    'ww1_germany_events.201.t': "Eleições do Reichstag de 1912",
    'ww1_germany_events.201.d': "As eleições gerais para o Reichstag resultaram em um abalo político profundo. O Partido Social-Democrata (SPD) ascendeu vertiginosamente, conquistando 110 deputados e tornando-se a maior bancada parlamentar. O Kaiser Wilhelm II e o gabinete enfrentam uma maioria decidida a exigir reformas democráticas.",
    'ww1_germany_events.201.a': "Buscar um entendimento com a maioria parlamentar.",
    'ww1_germany_events.201.b': "Unir as bancadas conservadoras para bloquear as reformas.",

    'ww1_germany_events.202.t': "Crise do Sufrágio Prussiano",
    'ww1_germany_events.202.d': "O sistema de voto de três classes na Prússia, que confere peso esmagador aos maiores contribuintes, enfrenta protestos furiosos em todo o império. Partidos liberais e sindicatos operários exigem sufrágio igualitário imediato, enquanto a aristocracia Junker ameaça resistência armada.",
    'ww1_germany_events.202.a': "Prometer reformas gradativas após a crise atual.",
    'ww1_germany_events.202.b': "A ordem prussiana é sagrada e imutável!",

    'ww1_germany_events.210.t': "O Spartakusbund em Revolta",
    'ww1_germany_events.210.d': "Karl Liebknecht, Rosa Luxemburg e os militantes antimilitaristas do Spartakusbund convocaram uma greve geral revolucionária. As autoridades imperiais perdem rapidamente o controle sobre os subúrbios operários de Berlim, Leipzig e Bremen.",
    'ww1_germany_events.210.a': "Abaixo a guerra imperialista! Todo o poder aos conselhos!",

    'ww1_germany_events.211.t': "Motim na Frota de Alto-Mar",
    'ww1_germany_events.211.d': "Marinheiros e foguistas nas bases navais de Kiel e Wilhelmshaven apagaram as caldeiras e hastearam bandeiras vermelhas nos mastros dos navios. Oficiais que tentaram impor ordem foram detidos pelos comitês eleitos de marinheiros.",
    'ww1_germany_events.211.a': "A frota vermelha pertence à revolução!",

    'ww1_germany_events.212.t': "Proclamação da República Socialista Livre",
    'ww1_germany_events.212.d': "Falando da sacada imperial do Stadtschloss em Berlim, Karl Liebknecht proclamou a República Socialista Livre da Alemanha. Conselhos de operários e soldados assumiram a administração pública em todas as grandes cidades.",
    'ww1_germany_events.212.a': "Viva a República dos Conselhos Alemã!",

    'ww1_germany_events.213.t': "O Tratado de Berlim Vermelha",
    'ww1_germany_events.213.d': "Delegados da Rússia Soviética chegaram a Berlim para ratificar um tratado abrangente de assistência mútua militar e comercial. A indústria alemã alia-se aos imensos recursos da república soviética russa.",
    'ww1_germany_events.213.a': "Ratificar a aliança fraterna socialista!",

    'ww1_germany_events.214.t': "A Federação Socialista Danubiana",
    'ww1_germany_events.214.d': "Inspirados por nossa revolução, a Guarda Vermelha austríaca e a República dos Conselhos Húngara de Béla Kun estabeleceram o poder operário em Viena e Budapeste, solicitando a integração à Federação Socialista Danubiana.",
    'ww1_germany_events.214.a': "Acolher nossos camaradas danubianos na federação!",

    'ww1_germany_events.220.t': "Proclamação da República Alemã",
    'ww1_germany_events.220.d': "De uma janela do edifício do Reichstag em Berlim, Philipp Scheidemann proclamou a República Democrática Alemã sob aplausos e aclamação popular. O imperador Wilhelm II abdicou de suas funções, e um governo provisório chefiado por Friedrich Ebert assumiu a administração.",
    'ww1_germany_events.220.a': "Viva a República Alemã!",

    'ww1_germany_events.221.t': "Negociações sob os Catorze Pontos de Wilson",
    'ww1_germany_events.221.d': "Nossa delegação diplomática contatou formalmente o presidente Woodrow Wilson, declarando a prontidão da Alemanha em negociar um armistício nos termos exatos dos Catorze Pontos, com base no direito de autodeterminação dos povos.",
    'ww1_germany_events.221.a': "Aceitar os Catorze Pontos como base definitiva para a paz.",
    'ww1_germany_events.221.b': "Exigir garantias coloniais antes de firmar o acordo.",

    'ww1_germany_events.222.t': "O Plebiscito na Alsácia-Lorena",
    'ww1_germany_events.222.d': "Em consonância com os preceitos democráticos, um referendo supervisionado internacionalmente foi conduzido na Alsácia-Lorena. A população manifestou sua vontade soberana, neutralizando disputas históricas com a França.",
    'ww1_germany_events.222.a': "Respeitar a vontade soberana das populações fronteiriças.",

    'ww1_germany_events.230.t': "A Terceira OHL Assume o Comando",
    'ww1_germany_events.230.d': "O Marechal Paul von Hindenburg e o General Erich Ludendorff assumiram controle incontestável do Alto Comando da Guerra (Oberste Heeresleitung). O Kaiser delegou todas as prerrogativas de comando, subordinando o gabinete à vitória.",
    'ww1_germany_events.230.a': "A vitória exige disciplina de ferro!",

    'ww1_germany_events.231.t': "Declaração de Guerra Submarina Irrestrita",
    'ww1_germany_events.231.d': "O Alto Comando determinou o retorno da guerra submarina irrestrita em todos os mares ao redor das Ilhas Britânicas. Toda navegação mercante será alvejada sem aviso prévio em uma tentativa decisiva de forçar o Reino Unido à capitulação.",
    'ww1_germany_events.231.a': "Que os submarinos imponham o bloqueio total!",
    'ww1_germany_events.231.b': "Considerar as advertências diplomáticas e manter as regras navais.",

    'ww1_germany_events.232.t': "O Desmembramento do Império Russo",
    'ww1_germany_events.232.d': "Após as vitórias em nossa frente oriental e os tratados de Brest-Litovsk, a Rússia cedeu extensas províncias na Polônia, Ucrânia, Belarus e nos Bálticos. Uma malha de estados satélites alemães é estabelecida para proteger nosso império.",
    'ww1_germany_events.232.a': "O Leste nos pertence!",

    'ww1_germany_events.240.t': "Fundação da Deutsche Vaterlandspartei",
    'ww1_germany_events.240.d': "O Grande Almirante Alfred von Tirpitz e Wolfgang Kapp fundaram a Deutsche Vaterlandspartei em Königsberg. Mais de um milhão de cidadãos filiaram-se em poucas semanas, exigindo a paz vitoriosa e anexações imperiais inegociáveis.",
    'ww1_germany_events.240.a': "Pelo Kaiser, pelo Povo e pela Glória Imperial!",

    'ww1_germany_events.241.t': "A Dissolução do Reichstag",
    'ww1_germany_events.241.d': "Diante da oposição de deputados liberais e socialistas, o governo dissolveu o Reichstag por decreto imperial. O império entra em estado de sítio absoluto, silenciando vozes divisionistas enquanto a guerra durar.",
    'ww1_germany_events.241.a': "A defesa nacional sobrepuja o debate parlamentar!",

    'ww1_germany_events.242.t': "Ultimato aos Países Baixos",
    'ww1_germany_events.242.d': "Nosso governo enviou um ultimato categórico ao governo holandês, exigindo a inclusão imediata da Holanda na rede aduaneira imperial alemã e acesso às instalações portuárias do delta do Reno.",
    'ww1_germany_events.242.a': "Eles devem acatar nossa vontade ou enfrentar nossa força!",

    # Ideas Localization
    'GER_wilhelmine_personal_regime': "Regime Pessoal Guilhermino",
    'GER_wilhelmine_reform_regime': "Constitucionalismo Guilhermino Reformado",
    'GER_volkerschlacht_spirit': "Espírito da Batalha das Nações",
    'GER_burgfrieden_1914': "Trégua Civil de Burgfrieden",
    'GER_rate_republik': "República Socialista dos Conselhos",
    'GER_red_commissars': "Conselhos de Soldados e Comissários",
    'GER_ruhr_proletariat': "Mobilização do Rote Ruhrarmee",
    'GER_world_revolution_vanguard': "Vanguarda da Revolução Mundial",
    'GER_weimar_democracy': "Constitucionalismo Democrático de Weimar",
    'GER_zollverein_subordination': "Subordinação ao Zollverein Alemão",
    'GER_hindenburg_program': "O Programa Hindenburg",
    'GER_operation_faustschlag_timed': "Ponta de Lança da Operação Faustschlag",
    'GER_continental_hegemony': "Hegemonia Continental Europeia",
    'GER_ohl_supreme_staff_coordination': "Coordenação Operacional da OHL",
    'GER_vaterlandspartei_movement': "Movimento de Massas Vaterlandspartei",
    'GER_siegfrieden_triumph': "Triunfo Imperial do Siegfrieden",

    # Decisions Localization
    'GER_council_republic_revolution': "Revolução Proletária dos Conselhos",
    'ger_council_nationalize_heavy_syndicates': "Nacionalizar Sindicatos Pesados",
    'ger_council_red_guard_militia_call': "Mobilizar Voluntários da Guarda Vermelha",
    'ger_council_propaganda_austria': "Agitar pelo Poder dos Conselhos Danubianos",
    'GER_weimar_democratic_diplomacy': "Diplomacia Democrática de Weimar",
    'ger_weimar_frankfurt_peace_congress': "Convocar Congresso de Paz em Frankfurt",
    'ger_weimar_expand_customs_treaty': "Expandir Tratado Aduaneiro Centro-Europeu",
    'ger_weimar_rhineland_pacification': "Pacificar a Renânia Industrial",
    'GER_ohl_total_mobilization': "Decretos de Mobilização Total da OHL",
    'ger_ohl_requisition_civilian_workshops': "Requisitar Oficinas Civis",
    'ger_ohl_enforce_labor_quotas': "Impor Cotas de Trabalho Auxiliar",
    'ger_ohl_deploy_sturmtruppen_spearhead': "Destacar Ponta de Lança das Sturmtruppen",
    'GER_pan_german_annexations': "Anexações e Colonização Pan-Germânica",
    'ger_pan_german_resettle_border_strip': "Povoar a Faixa de Fronteira Polonesa",
    'ger_pan_german_annex_antwerp_harbor': "Fortificar o Bastião de Antuérpia",
    'ger_pan_german_caucasus_oil_concession': "Extrair Petróleo de Baku",
}
