-- Keep the WW1 map style in 00_victorianization.lua and the native weather,
-- snow/mud, fog-of-war and aircraft animations. The former blanket zero
-- cutoffs removed the visual information needed to read terrain and weather.
-- Low-spec rendering options belong in the player's graphics settings; no
-- campaign-wide suppression is applied by this file.
