-- HOI4 1.19.3 native simulation scheduling is the reference baseline.
-- The previous overrides delayed research/template reviews by up to 60 days,
-- suppressed allied peace evaluation and contained undefined engine keys.
-- Keep native AI/diplomacy/log-retention and network lag limits while profiling
-- complete WW1 campaigns. Introduce measured optimisations individually.
